// permKey: 'op' | 'player' | 'mixed'
const COMMANDS = [
  {
    id: "flightexhaustion",
    root: "/flightexhaustion",
    permKey: "op",
    summary: {
      es: "Configura y consulta el sistema de fatiga de vuelo (agota vuelo creativo, élitro y/o vuelo racial tras un tiempo, con regeneración).",
      en: "Configures and inspects the flight exhaustion system (drains creative flight, elytra and/or racial flight over time, with regeneration).",
      pt: "Configura e consulta o sistema de fadiga de voo (esgota voo criativo, élitro e/ou voo racial com o tempo, com regeneração).",
      fr: "Configure et consulte le système de fatigue de vol (épuise le vol créatif, l'élytre et/ou le vol racial avec le temps, avec régénération).",
      de: "Konfiguriert und prüft das Flugerschöpfungssystem (erschöpft Kreativ-, Elytra- und/oder Rassenflug mit der Zeit, mit Regeneration).",
      it: "Configura e controlla il sistema di esaurimento del volo (esaurisce volo creativo, elitre e/o volo razziale nel tempo, con rigenerazione).",
      ru: "Настраивает и показывает состояние системы истощения полёта (со временем расходует творческий полёт, элитры и/или расовый полёт, с регенерацией).",
      ja: "飛行疲労システムを設定・確認します（クリエイティブ飛行、エリトラ、種族飛行を時間経過で消耗させ、回復もします）。",
      ko: "비행 피로도 시스템을 설정하고 확인합니다 (시간이 지나면 크리에이티브 비행, 엘리트라, 종족 비행을 소모시키며 회복도 됩니다).",
      zh: "配置并查看飞行疲劳系统（随时间消耗创造模式飞行、鞘翅和/或种族飞行，并带有恢复机制）。",
      ar: "يضبط ويعرض نظام إجهاد الطيران (يستهلك الطيران الإبداعي والإيليترا و/أو طيران العرق مع الوقت، مع إمكانية التجدد).",
      hi: "फ़्लाइट थकान सिस्टम को कॉन्फ़िगर और जाँचता है (समय के साथ क्रिएटिव फ़्लाइट, एलिट्रा और/या रेस फ़्लाइट को घटाता है, रीजेन के साथ)।",
      pl: "Konfiguruje i sprawdza system zmęczenia lotu (wyczerpuje lot kreatywny, lotki i/lub lot rasowy z czasem, z regeneracją).",
      tr: "Uçuş yorgunluğu sistemini yapılandırır ve kontrol eder (zamanla yaratıcı uçuşu, elytrayı ve/veya ırksal uçuşu tüketir, yenilenme ile).",
      nl: "Configureert en controleert het vluchtvermoeidheidssysteem (put creatieve vlucht, elytra en/of raciale vlucht na verloop van tijd uit, met regeneratie)."
    },
    subs: [
      { syntax: "/flightexhaustion", desc: {
        es: "Muestra el estado actual: duración, regeneración, mínimo para volar de nuevo y a qué afecta.",
        en: "Shows the current state: duration, regen, minimum to fly again, and what it affects.",
        pt: "Mostra o estado atual: duração, regeneração, mínimo para voar de novo e o que afeta.",
        fr: "Affiche l'état actuel : durée, régénération, minimum pour revoler et ce que ça affecte.",
        de: "Zeigt den aktuellen Status: Dauer, Regeneration, Minimum zum erneuten Fliegen und was betroffen ist.",
        it: "Mostra lo stato attuale: durata, rigenerazione, minimo per volare di nuovo e cosa influenza.",
        ru: "Показывает текущее состояние: длительность, регенерацию, минимум для повторного полёта и на что это влияет.",
        ja: "現在の状態（持続時間、回復量、再飛行に必要な最低値、対象）を表示します。",
        ko: "현재 상태(지속시간, 회복량, 재비행에 필요한 최소치, 영향 범위)를 표시합니다.",
        zh: "显示当前状态：持续时间、回复速度、再次飞行所需的最低值，以及影响范围。",
        ar: "يعرض الحالة الحالية: المدة، التجدد، الحد الأدنى للطيران مجددًا، وما يتأثر به.",
        hi: "वर्तमान स्थिति दिखाता है: अवधि, रीजेन, फिर से उड़ने के लिए न्यूनतम, और यह किसे प्रभावित करता है।",
        pl: "Pokazuje aktualny stan: czas trwania, regenerację, minimum do ponownego lotu i na co to wpływa.",
        tr: "Mevcut durumu gösterir: süre, yenilenme, tekrar uçmak için gereken minimum ve neyi etkilediği.",
        nl: "Toont de huidige status: duur, regeneratie, minimum om weer te vliegen en wat het beïnvloedt."
      } },
      { syntax: "/flightexhaustion duration <segundos>", desc: {
        es: "Cambia cuántos segundos de vuelo continuo se permiten antes de agotarse.",
        en: "Changes how many seconds of continuous flight are allowed before exhaustion.",
        pt: "Altera quantos segundos de voo contínuo são permitidos antes de esgotar.",
        fr: "Change le nombre de secondes de vol continu autorisées avant épuisement.",
        de: "Ändert, wie viele Sekunden Dauerflug vor der Erschöpfung erlaubt sind.",
        it: "Cambia quanti secondi di volo continuo sono permessi prima dell'esaurimento.",
        ru: "Изменяет количество секунд непрерывного полёта до истощения.",
        ja: "疲労するまでの連続飛行可能秒数を変更します。",
        ko: "피로해지기 전까지 허용되는 연속 비행 초를 변경합니다.",
        zh: "更改耗尽前允许的持续飞行秒数。",
        ar: "يغيّر عدد ثواني الطيران المتواصل المسموح بها قبل الإجهاد.",
        hi: "थकने से पहले लगातार उड़ान के कितने सेकंड की अनुमति है, यह बदलता है।",
        pl: "Zmienia liczbę sekund ciągłego lotu dozwoloną przed wyczerpaniem.",
        tr: "Yorgunluktan önce izin verilen kesintisiz uçuş saniyesini değiştirir.",
        nl: "Verandert hoeveel seconden aaneengesloten vliegen zijn toegestaan vóór vermoeidheid."
      } },
      { syntax: "/flightexhaustion regen <porcentaje>", desc: {
        es: "Cambia el % de regeneración de la reserva de vuelo.",
        en: "Changes the % regeneration rate of the flight reserve.",
        pt: "Altera a % de regeneração da reserva de voo.",
        fr: "Change le % de régénération de la réserve de vol.",
        de: "Ändert den prozentualen Regenerationswert der Flugreserve.",
        it: "Cambia la % di rigenerazione della riserva di volo.",
        ru: "Изменяет процент регенерации запаса полёта.",
        ja: "飛行ゲージの回復率（%）を変更します。",
        ko: "비행 게이지의 회복 비율(%)을 변경합니다.",
        zh: "更改飞行储备的恢复百分比。",
        ar: "يغيّر نسبة تجدد مخزون الطيران.",
        hi: "फ़्लाइट रिज़र्व की रीजेन % बदलता है।",
        pl: "Zmienia % regeneracji rezerwy lotu.",
        tr: "Uçuş rezervinin yenilenme yüzdesini değiştirir.",
        nl: "Verandert het regeneratiepercentage van de vluchtreserve."
      } },
      { syntax: "/flightexhaustion minimum <porcentaje>", desc: {
        es: "Cambia el % mínimo de energía necesario para poder volar de nuevo tras agotarse.",
        en: "Changes the minimum % of energy needed to fly again after exhaustion.",
        pt: "Altera a % mínima de energia necessária para voar de novo após esgotar.",
        fr: "Change le % minimum d'énergie nécessaire pour revoler après épuisement.",
        de: "Ändert den minimalen Energie-Prozentsatz, der nach Erschöpfung zum erneuten Fliegen nötig ist.",
        it: "Cambia la % minima di energia necessaria per volare di nuovo dopo l'esaurimento.",
        ru: "Изменяет минимальный процент энергии, необходимый для полёта после истощения.",
        ja: "疲労後に再び飛行するために必要な最低エネルギー％を変更します。",
        ko: "탈진 후 다시 비행하는 데 필요한 최소 에너지 %를 변경합니다.",
        zh: "更改耗尽后再次飞行所需的最低能量百分比。",
        ar: "يغيّر الحد الأدنى لنسبة الطاقة اللازمة للطيران مجددًا بعد الإجهاد.",
        hi: "थकने के बाद फिर से उड़ने के लिए आवश्यक न्यूनतम ऊर्जा % बदलता है।",
        pl: "Zmienia minimalny % energii potrzebny do ponownego lotu po wyczerpaniu.",
        tr: "Yorgunluktan sonra tekrar uçmak için gereken minimum enerji yüzdesini değiştirir.",
        nl: "Verandert het minimale energiepercentage dat nodig is om na uitputting weer te vliegen."
      } },
      { syntax: "/flightexhaustion affect creative <true|false>", desc: {
        es: "Activa/desactiva si el sistema afecta al vuelo creativo/racial.",
        en: "Toggles whether the system affects creative/racial flight.",
        pt: "Ativa/desativa se o sistema afeta o voo criativo/racial.",
        fr: "Active/désactive si le système affecte le vol créatif/racial.",
        de: "Schaltet um, ob das System den Kreativ-/Rassenflug betrifft.",
        it: "Attiva/disattiva se il sistema influisce sul volo creativo/razziale.",
        ru: "Включает/выключает влияние системы на творческий/расовый полёт.",
        ja: "システムがクリエイティブ／種族飛行に影響するかを切り替えます。",
        ko: "시스템이 크리에이티브/종족 비행에 영향을 주는지 전환합니다.",
        zh: "切换该系统是否影响创造模式/种族飞行。",
        ar: "يبدّل ما إذا كان النظام يؤثر على الطيران الإبداعي/العرقي.",
        hi: "सिस्टम क्रिएटिव/रेस फ़्लाइट को प्रभावित करे या नहीं, यह टॉगल करता है।",
        pl: "Przełącza, czy system wpływa na lot kreatywny/rasowy.",
        tr: "Sistemin yaratıcı/ırksal uçuşu etkileyip etkilemediğini değiştirir.",
        nl: "Schakelt in/uit of het systeem creatieve/raciale vlucht beïnvloedt."
      } },
      { syntax: "/flightexhaustion affect elytra <true|false>", desc: {
        es: "Activa/desactiva si afecta al élitro.",
        en: "Toggles whether it affects elytra flight.",
        pt: "Ativa/desativa se afeta o voo com élitro.",
        fr: "Active/désactive si ça affecte le vol en élytre.",
        de: "Schaltet um, ob der Elytra-Flug betroffen ist.",
        it: "Attiva/disattiva se influisce sul volo con elitre.",
        ru: "Включает/выключает влияние на полёт на элитрах.",
        ja: "エリトラ飛行に影響するかを切り替えます。",
        ko: "엘리트라 비행에 영향을 주는지 전환합니다.",
        zh: "切换是否影响鞘翅飞行。",
        ar: "يبدّل ما إذا كان يؤثر على طيران الإيليترا.",
        hi: "यह एलिट्रा उड़ान को प्रभावित करे या नहीं, टॉगल करता है।",
        pl: "Przełącza, czy wpływa na lot lotkami.",
        tr: "Elytra uçuşunu etkileyip etkilemediğini değiştirir.",
        nl: "Schakelt in/uit of het elytravlucht beïnvloedt."
      } },
      { syntax: "/flightexhaustion affect airflight <true|false>", desc: {
        es: "Activa/desactiva si afecta al vuelo aéreo (skill de Tensura).",
        en: "Toggles whether it affects Air Flight (the Tensura skill).",
        pt: "Ativa/desativa se afeta o Air Flight (skill do Tensura).",
        fr: "Active/désactive si ça affecte l'Air Flight (compétence Tensura).",
        de: "Schaltet um, ob Air Flight (die Tensura-Fähigkeit) betroffen ist.",
        it: "Attiva/disattiva se influisce sull'Air Flight (abilità di Tensura).",
        ru: "Включает/выключает влияние на Air Flight (навык Tensura).",
        ja: "エアフライト（Tensuraのスキル）に影響するかを切り替えます。",
        ko: "에어 플라이트(텐스라 스킬)에 영향을 주는지 전환합니다.",
        zh: "切换是否影响空中飞行（Tensura 技能）。",
        ar: "يبدّل ما إذا كان يؤثر على Air Flight (مهارة Tensura).",
        hi: "यह एयर फ़्लाइट (Tensura स्किल) को प्रभावित करे या नहीं, टॉगल करता है।",
        pl: "Przełącza, czy wpływa na Air Flight (umiejętność Tensura).",
        tr: "Air Flight'ı (Tensura yeteneği) etkileyip etkilemediğini değiştirir.",
        nl: "Schakelt in/uit of het Air Flight (de Tensura-skill) beïnvloedt."
      } },
      { syntax: "/flightexhaustion reset", desc: {
        es: "Restaura los valores por defecto (30s duración / 15% regen / 30% mínimo).",
        en: "Restores the default values (30s duration / 15% regen / 30% minimum).",
        pt: "Restaura os valores padrão (30s duração / 15% regen / 30% mínimo).",
        fr: "Restaure les valeurs par défaut (30s durée / 15% régén / 30% minimum).",
        de: "Stellt die Standardwerte wieder her (30s Dauer / 15% Regen / 30% Minimum).",
        it: "Ripristina i valori predefiniti (30s durata / 15% rigen / 30% minimo).",
        ru: "Восстанавливает значения по умолчанию (30с длительность / 15% регенерация / 30% минимум).",
        ja: "デフォルト値に戻します（持続30秒／回復15%／最低30%）。",
        ko: "기본값으로 복원합니다 (지속 30초 / 회복 15% / 최소 30%).",
        zh: "恢复默认值（持续30秒 / 回复15% / 最低30%）。",
        ar: "يعيد القيم الافتراضية (30 ثانية مدة / 15% تجدد / 30% حد أدنى).",
        hi: "डिफ़ॉल्ट मान बहाल करता है (30s अवधि / 15% रीजेन / 30% न्यूनतम)।",
        pl: "Przywraca wartości domyślne (30s czas trwania / 15% regeneracji / 30% minimum).",
        tr: "Varsayılan değerleri geri yükler (30s süre / %15 yenilenme / %30 minimum).",
        nl: "Herstelt de standaardwaarden (30s duur / 15% regen / 30% minimum)."
      } }
    ]
  },
  {
    id: "minesura",
    root: "/minesura",
    permKey: "mixed",
    summary: {
      es: "Comando principal del mod: nobleza/reinos, True Name Trial, rerolls de skill única, y utilidades de administración.",
      en: "The mod's main command: nobility/kingdoms, the True Name Trial, unique skill rerolls, and admin utilities.",
      pt: "Comando principal do mod: nobreza/reinos, True Name Trial, rerolls de skill única, e utilitários de administração.",
      fr: "Commande principale du mod : noblesse/royaumes, le True Name Trial, les rerolls de skill unique, et les outils d'administration.",
      de: "Der Hauptbefehl des Mods: Adel/Königreiche, die True Name Trial, Unique-Skill-Rerolls und Admin-Werkzeuge.",
      it: "Comando principale della mod: nobiltà/regni, la True Name Trial, i reroll delle unique skill e strumenti di amministrazione.",
      ru: "Главная команда мода: дворянство/королевства, испытание True Name Trial, реролл уникальных навыков и утилиты администрирования.",
      ja: "MODのメインコマンド：貴族/王国、True Name Trial、ユニークスキルの再抽選、管理用ユーティリティ。",
      ko: "모드의 메인 명령어: 귀족/왕국, True Name Trial, 유니크 스킬 리롤, 관리 도구.",
      zh: "模组的主指令：贵族/王国、True Name Trial、固有技能重抽，以及管理工具。",
      ar: "الأمر الرئيسي للمود: النبلاء/الممالك، تجربة True Name Trial، إعادة عشوائية المهارة الفريدة، وأدوات الإدارة.",
      hi: "मॉड का मुख्य कमांड: नोबिलिटी/किंगडम, ट्रू नेम ट्रायल, यूनिक स्किल रीरोल, और एडमिन उपयोगिताएँ।",
      pl: "Główna komenda moda: szlachta/królestwa, True Name Trial, rerolle unique skill oraz narzędzia administracyjne.",
      tr: "Modun ana komutu: soyluluk/krallıklar, True Name Trial, unique skill reroll'ları ve yönetici araçları.",
      nl: "Het hoofdcommando van de mod: adel/koninkrijken, de True Name Trial, unique skill rerolls en beheertools."
    },
    subs: [
      { syntax: "/minesura nobility found <nombre>", desc: {
        es: "Funda un reino/nobleza con el nombre indicado.",
        en: "Founds a kingdom/nobility with the given name.",
        pt: "Funda um reino/nobreza com o nome indicado.",
        fr: "Fonde un royaume/noblesse avec le nom indiqué.",
        de: "Gründet ein Königreich/Adelshaus mit dem angegebenen Namen.",
        it: "Fonda un regno/nobiltà con il nome indicato.",
        ru: "Основывает королевство/дворянский дом с указанным именем.",
        ja: "指定した名前で王国／貴族家を創設します。",
        ko: "지정한 이름으로 왕국/귀족가를 창설합니다.",
        zh: "以指定名称建立一个王国/贵族家系。",
        ar: "يؤسس مملكة/بيت نبلاء بالاسم المحدد.",
        hi: "दिए गए नाम से एक किंगडम/नोबिलिटी स्थापित करता है।",
        pl: "Zakłada królestwo/ród szlachecki o podanej nazwie.",
        tr: "Belirtilen isimle bir krallık/soyluluk kurar.",
        nl: "Sticht een koninkrijk/adelshuis met de opgegeven naam."
      } },
      { syntax: "/minesura nobility grant <jugador> <título>", desc: {
        es: "(op) Concede un título de nobleza a un jugador.",
        en: "(op) Grants a nobility title to a player.",
        pt: "(op) Concede um título de nobreza a um jogador.",
        fr: "(op) Accorde un titre de noblesse à un joueur.",
        de: "(op) Verleiht einem Spieler einen Adelstitel.",
        it: "(op) Concede un titolo nobiliare a un giocatore.",
        ru: "(op) Присваивает игроку дворянский титул.",
        ja: "(op) プレイヤーに貴族の称号を与えます。",
        ko: "(op) 플레이어에게 귀족 작위를 부여합니다.",
        zh: "(op) 授予玩家一个贵族头衔。",
        ar: "(op) يمنح لقب نبالة للاعب.",
        hi: "(op) एक खिलाड़ी को नोबिलिटी टाइटल प्रदान करता है।",
        pl: "(op) Nadaje graczowi tytuł szlachecki.",
        tr: "(op) Bir oyuncuya soyluluk unvanı verir.",
        nl: "(op) Kent een adellijke titel toe aan een speler."
      } },
      { syntax: "/minesura nobility revoke <jugador>", desc: {
        es: "(op) Revoca el título de nobleza de un jugador.",
        en: "(op) Revokes a player's nobility title.",
        pt: "(op) Revoga o título de nobreza de um jogador.",
        fr: "(op) Révoque le titre de noblesse d'un joueur.",
        de: "(op) Entzieht einem Spieler den Adelstitel.",
        it: "(op) Revoca il titolo nobiliare di un giocatore.",
        ru: "(op) Отзывает дворянский титул игрока.",
        ja: "(op) プレイヤーの貴族称号を剥奪します。",
        ko: "(op) 플레이어의 귀족 작위를 박탈합니다.",
        zh: "(op) 撤销玩家的贵族头衔。",
        ar: "(op) يسحب لقب النبالة من اللاعب.",
        hi: "(op) एक खिलाड़ी का नोबिलिटी टाइटल रद्द करता है।",
        pl: "(op) Odbiera graczowi tytuł szlachecki.",
        tr: "(op) Bir oyuncunun soyluluk unvanını iptal eder.",
        nl: "(op) Trekt de adellijke titel van een speler in."
      } },
      { syntax: "/minesura nobility rename <nombre>", desc: {
        es: "Renombra tu reino.",
        en: "Renames your kingdom.",
        pt: "Renomeia o seu reino.",
        fr: "Renomme votre royaume.",
        de: "Benennt dein Königreich um.",
        it: "Rinomina il tuo regno.",
        ru: "Переименовывает ваше королевство.",
        ja: "自分の王国名を変更します。",
        ko: "자신의 왕국 이름을 변경합니다.",
        zh: "重命名你的王国。",
        ar: "يعيد تسمية مملكتك.",
        hi: "आपके किंगडम का नाम बदलता है।",
        pl: "Zmienia nazwę twojego królestwa.",
        tr: "Krallığının adını değiştirir.",
        nl: "Hernoemt jouw koninkrijk."
      } },
      { syntax: "/minesura nobility leave", desc: {
        es: "Abandona tu reino/nobleza actual.",
        en: "Leaves your current kingdom/nobility.",
        pt: "Abandona o seu reino/nobreza atual.",
        fr: "Quitte votre royaume/noblesse actuel.",
        de: "Verlässt dein aktuelles Königreich/Adelshaus.",
        it: "Abbandona il tuo regno/nobiltà attuale.",
        ru: "Покидает текущее королевство/дворянский дом.",
        ja: "現在の王国／貴族家を脱退します。",
        ko: "현재 왕국/귀족가를 탈퇴합니다.",
        zh: "离开你当前所属的王国/贵族家系。",
        ar: "يغادر مملكتك/بيت نبلائك الحالي.",
        hi: "आपके वर्तमान किंगडम/नोबिलिटी को छोड़ता है।",
        pl: "Opuszcza twoje obecne królestwo/ród szlachecki.",
        tr: "Mevcut krallığından/soyluluğundan ayrılır.",
        nl: "Verlaat jouw huidige koninkrijk/adelshuis."
      } },
      { syntax: "/minesura nobility disband", desc: {
        es: "Disuelve tu reino (si eres el líder).",
        en: "Disbands your kingdom (if you're the leader).",
        pt: "Dissolve o seu reino (se você for o líder).",
        fr: "Dissout votre royaume (si vous êtes le chef).",
        de: "Löst dein Königreich auf (wenn du der Anführer bist).",
        it: "Scioglie il tuo regno (se sei il leader).",
        ru: "Распускает ваше королевство (если вы лидер).",
        ja: "自分の王国を解散します（リーダーの場合のみ）。",
        ko: "자신의 왕국을 해체합니다 (리더인 경우).",
        zh: "解散你的王国（如果你是领袖）。",
        ar: "يحل مملكتك (إذا كنت القائد).",
        hi: "आपके किंगडम को भंग करता है (यदि आप लीडर हैं)।",
        pl: "Rozwiązuje twoje królestwo (jeśli jesteś liderem).",
        tr: "Krallığını dağıtır (lider isen).",
        nl: "Ontbindt jouw koninkrijk (als je de leider bent)."
      } },
      { syntax: "/minesura nobility info [jugador]", desc: {
        es: "Muestra información de nobleza propia o de otro jugador.",
        en: "Shows your own or another player's nobility info.",
        pt: "Mostra informações de nobreza próprias ou de outro jogador.",
        fr: "Affiche les informations de noblesse, les vôtres ou celles d'un autre joueur.",
        de: "Zeigt deine eigenen oder die Adelsinfos eines anderen Spielers.",
        it: "Mostra le informazioni nobiliari tue o di un altro giocatore.",
        ru: "Показывает информацию о дворянстве — вашем или другого игрока.",
        ja: "自分または他プレイヤーの貴族情報を表示します。",
        ko: "본인 또는 다른 플레이어의 귀족 정보를 표시합니다.",
        zh: "显示你自己或另一名玩家的贵族信息。",
        ar: "يعرض معلومات النبالة الخاصة بك أو بلاعب آخر.",
        hi: "आपकी अपनी या किसी अन्य खिलाड़ी की नोबिलिटी जानकारी दिखाता है।",
        pl: "Pokazuje informacje o szlachectwie — twoje lub innego gracza.",
        tr: "Kendi veya başka bir oyuncunun soyluluk bilgisini gösterir.",
        nl: "Toont jouw eigen adelsinformatie of die van een andere speler."
      } },
      { syntax: "/minesura nobility admin crown <jugador> <reino>", desc: {
        es: "(op) Corona a un jugador rey/líder de un reino.",
        en: "(op) Crowns a player as king/leader of a kingdom.",
        pt: "(op) Coroa um jogador como rei/líder de um reino.",
        fr: "(op) Couronne un joueur roi/chef d'un royaume.",
        de: "(op) Krönt einen Spieler zum König/Anführer eines Königreichs.",
        it: "(op) Incorona un giocatore re/leader di un regno.",
        ru: "(op) Коронует игрока королём/лидером королевства.",
        ja: "(op) プレイヤーを王国の王／リーダーに任命します。",
        ko: "(op) 플레이어를 왕국의 왕/리더로 즉위시킵니다.",
        zh: "(op) 加冕玩家为某王国的国王/领袖。",
        ar: "(op) يتوّج لاعبًا ملكًا/قائدًا لمملكة.",
        hi: "(op) एक खिलाड़ी को किंगडम का राजा/लीडर बनाता है।",
        pl: "(op) Koronuje gracza na króla/lidera królestwa.",
        tr: "(op) Bir oyuncuyu bir krallığın kralı/lideri olarak taçlandırır.",
        nl: "(op) Kroont een speler tot koning/leider van een koninkrijk."
      } },
      { syntax: "/minesura nobility admin disband <reino>", desc: {
        es: "(op) Disuelve un reino a la fuerza.",
        en: "(op) Forcibly disbands a kingdom.",
        pt: "(op) Dissolve um reino à força.",
        fr: "(op) Dissout de force un royaume.",
        de: "(op) Löst ein Königreich zwangsweise auf.",
        it: "(op) Scioglie forzatamente un regno.",
        ru: "(op) Принудительно распускает королевство.",
        ja: "(op) 王国を強制的に解散させます。",
        ko: "(op) 왕국을 강제로 해체합니다.",
        zh: "(op) 强制解散一个王国。",
        ar: "(op) يحل مملكة قسرًا.",
        hi: "(op) एक किंगडम को जबरन भंग करता है।",
        pl: "(op) Wymusza rozwiązanie królestwa.",
        tr: "(op) Bir krallığı zorla dağıtır.",
        nl: "(op) Ontbindt een koninkrijk gedwongen."
      } },
      { syntax: "/minesura nobility admin remove <jugador>", desc: {
        es: "(op) Expulsa a un jugador de su reino.",
        en: "(op) Removes a player from their kingdom.",
        pt: "(op) Remove um jogador do seu reino.",
        fr: "(op) Exclut un joueur de son royaume.",
        de: "(op) Entfernt einen Spieler aus seinem Königreich.",
        it: "(op) Rimuove un giocatore dal suo regno.",
        ru: "(op) Исключает игрока из его королевства.",
        ja: "(op) プレイヤーを王国から追放します。",
        ko: "(op) 플레이어를 왕국에서 추방합니다.",
        zh: "(op) 将玩家从其王国中移除。",
        ar: "(op) يطرد لاعبًا من مملكته.",
        hi: "(op) एक खिलाड़ी को उसके किंगडम से निकालता है।",
        pl: "(op) Usuwa gracza z jego królestwa.",
        tr: "(op) Bir oyuncuyu krallığından çıkarır.",
        nl: "(op) Verwijdert een speler uit zijn koninkrijk."
      } },
      { syntax: "/minesura truename start", desc: {
        es: "Inicia el True Name Trial para el jugador.",
        en: "Starts the True Name Trial for the player.",
        pt: "Inicia o True Name Trial para o jogador.",
        fr: "Démarre le True Name Trial pour le joueur.",
        de: "Startet die True Name Trial für den Spieler.",
        it: "Avvia la True Name Trial per il giocatore.",
        ru: "Запускает испытание True Name Trial для игрока.",
        ja: "プレイヤーのTrue Name Trialを開始します。",
        ko: "플레이어의 True Name Trial을 시작합니다.",
        zh: "为玩家开始 True Name Trial（真名试炼）。",
        ar: "يبدأ True Name Trial للاعب.",
        hi: "खिलाड़ी के लिए ट्रू नेम ट्रायल शुरू करता है।",
        pl: "Rozpoczyna True Name Trial dla gracza.",
        tr: "Oyuncu için True Name Trial'ı başlatır.",
        nl: "Start de True Name Trial voor de speler."
      } },
      { syntax: "/minesura truename status", desc: {
        es: "Consulta si estás en el trial o si ya lo completaste.",
        en: "Checks whether you're in the trial or have completed it.",
        pt: "Verifica se você está no trial ou já o completou.",
        fr: "Vérifie si vous êtes dans l'épreuve ou si vous l'avez déjà terminée.",
        de: "Prüft, ob du dich in der Prüfung befindest oder sie abgeschlossen hast.",
        it: "Controlla se sei nella prova o l'hai già completata.",
        ru: "Проверяет, находитесь ли вы в испытании или уже завершили его.",
        ja: "トライアル中か、既に完了しているかを確認します。",
        ko: "트라이얼 진행 중인지, 이미 완료했는지 확인합니다.",
        zh: "查询你是否正在试炼中或已经完成。",
        ar: "يتحقق مما إذا كنت في التجربة أو أكملتها.",
        hi: "जाँचता है कि आप ट्रायल में हैं या इसे पूरा कर चुके हैं।",
        pl: "Sprawdza, czy jesteś w próbie lub ją ukończyłeś.",
        tr: "Denemede olup olmadığınızı veya tamamlayıp tamamlamadığınızı kontrol eder.",
        nl: "Controleert of je in de proef zit of deze al hebt voltooid."
      } },
      { syntax: "/minesura truename reset <jugador>", desc: {
        es: "(op) Reinicia el progreso del True Name Trial de un jugador.",
        en: "(op) Resets a player's True Name Trial progress.",
        pt: "(op) Reinicia o progresso do True Name Trial de um jogador.",
        fr: "(op) Réinitialise la progression du True Name Trial d'un joueur.",
        de: "(op) Setzt den Fortschritt der True Name Trial eines Spielers zurück.",
        it: "(op) Reimposta il progresso della True Name Trial di un giocatore.",
        ru: "(op) Сбрасывает прогресс испытания True Name Trial у игрока.",
        ja: "(op) プレイヤーのTrue Name Trial進行状況をリセットします。",
        ko: "(op) 플레이어의 True Name Trial 진행 상황을 초기화합니다.",
        zh: "(op) 重置玩家的 True Name Trial 进度。",
        ar: "(op) يعيد ضبط تقدم True Name Trial للاعب.",
        hi: "(op) एक खिलाड़ी की ट्रू नेम ट्रायल प्रगति रीसेट करता है।",
        pl: "(op) Resetuje postęp True Name Trial gracza.",
        tr: "(op) Bir oyuncunun True Name Trial ilerlemesini sıfırlar.",
        nl: "(op) Zet de voortgang van de True Name Trial van een speler terug."
      } },
      { syntax: "/minesura rerolls get <jugador>", desc: {
        es: "(op) Consulta cuántos rerolls de skill única ha usado un jugador.",
        en: "(op) Checks how many unique skill rerolls a player has used.",
        pt: "(op) Verifica quantos rerolls de skill única um jogador usou.",
        fr: "(op) Vérifie combien de rerolls de skill unique un joueur a utilisés.",
        de: "(op) Prüft, wie viele Unique-Skill-Rerolls ein Spieler verbraucht hat.",
        it: "(op) Controlla quanti reroll di unique skill ha usato un giocatore.",
        ru: "(op) Проверяет, сколько реролов уникального навыка использовал игрок.",
        ja: "(op) プレイヤーが使用したユニークスキルの再抽選回数を確認します。",
        ko: "(op) 플레이어가 사용한 유니크 스킬 리롤 횟수를 확인합니다.",
        zh: "(op) 查询玩家已使用的固有技能重抽次数。",
        ar: "(op) يتحقق من عدد مرات إعادة العشوائية للمهارة الفريدة التي استخدمها اللاعب.",
        hi: "(op) एक खिलाड़ी ने कितने यूनिक स्किल रीरोल इस्तेमाल किए हैं, जाँचता है।",
        pl: "(op) Sprawdza, ile rerollów unique skill wykorzystał gracz.",
        tr: "(op) Bir oyuncunun kaç unique skill reroll'u kullandığını kontrol eder.",
        nl: "(op) Controleert hoeveel unique skill rerolls een speler heeft gebruikt."
      } },
      { syntax: "/minesura rerolls set <jugador> <cantidad>", desc: {
        es: "(op) Fija el número de rerolls usados por un jugador.",
        en: "(op) Sets the number of rerolls a player has used.",
        pt: "(op) Define o número de rerolls usados por um jogador.",
        fr: "(op) Définit le nombre de rerolls utilisés par un joueur.",
        de: "(op) Legt die Anzahl der von einem Spieler verbrauchten Rerolls fest.",
        it: "(op) Imposta il numero di reroll usati da un giocatore.",
        ru: "(op) Устанавливает количество использованных реролов у игрока.",
        ja: "(op) プレイヤーが使用した再抽選回数を設定します。",
        ko: "(op) 플레이어가 사용한 리롤 횟수를 설정합니다.",
        zh: "(op) 设置玩家已使用的重抽次数。",
        ar: "(op) يحدد عدد مرات إعادة العشوائية التي استخدمها لاعب.",
        hi: "(op) एक खिलाड़ी द्वारा उपयोग किए गए रीरोल की संख्या सेट करता है।",
        pl: "(op) Ustawia liczbę rerollów wykorzystanych przez gracza.",
        tr: "(op) Bir oyuncunun kullandığı reroll sayısını ayarlar.",
        nl: "(op) Stelt het aantal door een speler gebruikte rerolls in."
      } },
      { syntax: "/minesura rerolls reset <jugador>", desc: {
        es: "(op) Reinicia los rerolls usados de un jugador a 0.",
        en: "(op) Resets a player's used rerolls to 0.",
        pt: "(op) Reinicia os rerolls usados de um jogador para 0.",
        fr: "(op) Réinitialise à 0 les rerolls utilisés par un joueur.",
        de: "(op) Setzt die verbrauchten Rerolls eines Spielers auf 0 zurück.",
        it: "(op) Reimposta a 0 i reroll usati da un giocatore.",
        ru: "(op) Сбрасывает использованные реролы игрока в 0.",
        ja: "(op) プレイヤーの使用済み再抽選回数を0にリセットします。",
        ko: "(op) 플레이어가 사용한 리롤 수를 0으로 초기화합니다.",
        zh: "(op) 将玩家已使用的重抽次数重置为 0。",
        ar: "(op) يعيد ضبط عدد مرات إعادة العشوائية المستخدمة للاعب إلى 0.",
        hi: "(op) एक खिलाड़ी के उपयोग किए गए रीरोल को 0 पर रीसेट करता है।",
        pl: "(op) Resetuje wykorzystane rerolle gracza do 0.",
        tr: "(op) Bir oyuncunun kullandığı reroll sayısını 0'a sıfırlar.",
        nl: "(op) Zet de gebruikte rerolls van een speler terug naar 0."
      } },
      { syntax: "/minesura grant_unique <jugador> <id_skill>", desc: {
        es: "(op) Otorga directamente una Unique Skill por su id de registro (ej. tensura_minesura:windcaller).",
        en: "(op) Directly grants a Unique Skill by its registry id (e.g. tensura_minesura:windcaller).",
        pt: "(op) Concede diretamente uma Unique Skill pelo seu id de registro (ex. tensura_minesura:windcaller).",
        fr: "(op) Accorde directement une Unique Skill via son id de registre (ex. tensura_minesura:windcaller).",
        de: "(op) Verleiht direkt eine Unique Skill über ihre Registry-ID (z. B. tensura_minesura:windcaller).",
        it: "(op) Concede direttamente una Unique Skill tramite il suo id di registro (es. tensura_minesura:windcaller).",
        ru: "(op) Напрямую выдаёт Unique Skill по её реестровому id (напр. tensura_minesura:windcaller).",
        ja: "(op) レジストリID（例: tensura_minesura:windcaller）でユニークスキルを直接付与します。",
        ko: "(op) 레지스트리 ID(예: tensura_minesura:windcaller)로 유니크 스킬을 직접 부여합니다.",
        zh: "(op) 通过注册表 id（如 tensura_minesura:windcaller）直接授予一个固有技能。",
        ar: "(op) يمنح مباشرة مهارة فريدة عبر معرّف التسجيل الخاص بها (مثال: tensura_minesura:windcaller).",
        hi: "(op) रजिस्ट्री id (जैसे tensura_minesura:windcaller) से सीधे एक यूनिक स्किल देता है।",
        pl: "(op) Bezpośrednio nadaje Unique Skill po jej id rejestru (np. tensura_minesura:windcaller).",
        tr: "(op) Kayıt id'siyle (örn. tensura_minesura:windcaller) doğrudan bir Unique Skill verir.",
        nl: "(op) Kent direct een Unique Skill toe via zijn registry-id (bijv. tensura_minesura:windcaller)."
      } },
      { syntax: "/minesura awaken_surtr <jugador>", desc: {
        es: "(op) Fuerza el despertar de Ragnarok's Herald en Surtr para un jugador que ya la tenga maestreada (normalmente requiere haber matado a 9 jugadores).",
        en: "(op) Forces the awakening of a mastered Ragnarok's Herald into Surtr for a player (normally requires killing 9 players).",
        pt: "(op) Força o despertar de Ragnarok's Herald em Surtr para um jogador que já a tenha maestreado (normalmente requer matar 9 jogadores).",
        fr: "(op) Force l'éveil de Ragnarok's Herald en Surtr pour un joueur qui l'a déjà maîtrisée (nécessite normalement d'avoir tué 9 joueurs).",
        de: "(op) Erzwingt das Erwachen einer gemeisterten Ragnarok's Herald zu Surtr für einen Spieler (normalerweise erfordert das Töten von 9 Spielern).",
        it: "(op) Forza il risveglio di Ragnarok's Herald in Surtr per un giocatore che l'ha già maestrata (normalmente richiede l'uccisione di 9 giocatori).",
        ru: "(op) Принудительно пробуждает освоенный Ragnarok's Herald в Surtr для игрока (обычно требуется убийство 9 игроков).",
        ja: "(op) 既にマスターしたRagnarok's Heraldを持つプレイヤーに対し、Surtrへの覚醒を強制します（通常はプレイヤーを9人倒す必要があります）。",
        ko: "(op) 이미 마스터한 Ragnarok's Herald를 가진 플레이어에게 Surtr로의 각성을 강제로 부여합니다 (보통 플레이어 9명 처치가 필요).",
        zh: "(op) 为已精通 Ragnarok's Herald 的玩家强制觉醒为 Surtr（通常需要击杀 9 名玩家）。",
        ar: "(op) يفرض صحوة Ragnarok's Herald المتقنة إلى Surtr للاعب (يتطلب عادةً قتل 9 لاعبين).",
        hi: "(op) पहले से माहिर Ragnarok's Herald वाले खिलाड़ी के लिए Surtr में जागृति को बलपूर्वक कराता है (आमतौर पर 9 खिलाड़ियों को मारना आवश्यक है)।",
        pl: "(op) Wymusza przebudzenie opanowanego Ragnarok's Herald w Surtr dla gracza (zwykle wymaga zabicia 9 graczy).",
        tr: "(op) Ustalaşılmış Ragnarok's Herald'ı zaten olan bir oyuncu için Surtr'a uyanışı zorlar (genellikle 9 oyuncu öldürmeyi gerektirir).",
        nl: "(op) Dwingt het ontwaken van een gemasterde Ragnarok's Herald tot Surtr af voor een speler (vereist normaal het doden van 9 spelers)."
      } }
    ]
  },
  {
    id: "epgain",
    root: "/epgain",
    permKey: "op",
    summary: {
      es: "Consulta o ajusta el multiplicador de ganancia de Magicule (MP) y Aura (AP) de un jugador.",
      en: "Checks or adjusts a player's Magicule (MP) and Aura (AP) gain multiplier.",
      pt: "Consulta ou ajusta o multiplicador de ganho de Magicule (MP) e Aura (AP) de um jogador.",
      fr: "Vérifie ou ajuste le multiplicateur de gain de Magicule (MP) et d'Aura (AP) d'un joueur.",
      de: "Prüft oder passt den Magicule- (MP) und Aura- (AP) Zuwachsmultiplikator eines Spielers an.",
      it: "Controlla o regola il moltiplicatore di guadagno di Magicule (MP) e Aura (AP) di un giocatore.",
      ru: "Проверяет или изменяет множитель прироста Magicule (MP) и Aura (AP) игрока.",
      ja: "プレイヤーのマジキュル(MP)とオーラ(AP)獲得倍率を確認・調整します。",
      ko: "플레이어의 마기큘(MP)과 오라(AP) 획득 배율을 확인하거나 조정합니다.",
      zh: "查看或调整玩家的魔素（MP）和斗气（AP）获取倍率。",
      ar: "يتحقق من أو يعدّل مضاعف اكتساب Magicule (MP) وAura (AP) للاعب.",
      hi: "एक खिलाड़ी के मैजिक्यूल (MP) और आभा (AP) गेन मल्टीप्लायर को जाँचता या समायोजित करता है।",
      pl: "Sprawdza lub zmienia mnożnik zdobywania Magicule (MP) i Aury (AP) gracza.",
      tr: "Bir oyuncunun Magicule (MP) ve Aura (AP) kazanım çarpanını kontrol eder veya ayarlar.",
      nl: "Controleert of past de Magicule- (MP) en Aura- (AP) winstmultiplier van een speler aan."
    },
    subs: [
      { syntax: "/epgain <jugador> get mp", desc: {
        es: "Muestra la ganancia base y efectiva de Magicule del jugador.",
        en: "Shows the player's base and effective Magicule gain.",
        pt: "Mostra o ganho base e efetivo de Magicule do jogador.",
        fr: "Affiche le gain de base et effectif de Magicule du joueur.",
        de: "Zeigt den Basis- und effektiven Magicule-Zuwachs des Spielers.",
        it: "Mostra il guadagno base ed effettivo di Magicule del giocatore.",
        ru: "Показывает базовый и эффективный прирост Magicule игрока.",
        ja: "プレイヤーの基礎マジキュル獲得量と実効値を表示します。",
        ko: "플레이어의 기본 및 실질 마기큘 획득량을 표시합니다.",
        zh: "显示玩家的基础和实际魔素获取量。",
        ar: "يعرض اكتساب Magicule الأساسي والفعلي للاعب.",
        hi: "खिलाड़ी का बेस और इफेक्टिव मैजिक्यूल गेन दिखाता है।",
        pl: "Pokazuje bazowe i efektywne zdobywanie Magicule gracza.",
        tr: "Oyuncunun temel ve etkin Magicule kazanımını gösterir.",
        nl: "Toont de basis- en effectieve Magicule-winst van de speler."
      } },
      { syntax: "/epgain <jugador> get ap", desc: {
        es: "Muestra la ganancia base y efectiva de Aura del jugador.",
        en: "Shows the player's base and effective Aura gain.",
        pt: "Mostra o ganho base e efetivo de Aura do jogador.",
        fr: "Affiche le gain de base et effectif d'Aura du joueur.",
        de: "Zeigt den Basis- und effektiven Aura-Zuwachs des Spielers.",
        it: "Mostra il guadagno base ed effettivo di Aura del giocatore.",
        ru: "Показывает базовый и эффективный прирост Aura игрока.",
        ja: "プレイヤーの基礎オーラ獲得量と実効値を表示します。",
        ko: "플레이어의 기본 및 실질 오라 획득량을 표시합니다.",
        zh: "显示玩家的基础和实际斗气获取量。",
        ar: "يعرض اكتساب Aura الأساسي والفعلي للاعب.",
        hi: "खिलाड़ी का बेस और इफेक्टिव आभा गेन दिखाता है।",
        pl: "Pokazuje bazowe i efektywne zdobywanie Aury gracza.",
        tr: "Oyuncunun temel ve etkin Aura kazanımını gösterir.",
        nl: "Toont de basis- en effectieve Aura-winst van de speler."
      } },
      { syntax: "/epgain <jugador> set mp <valor>", desc: {
        es: "Fija el atributo base de ganancia de Magicule del jugador.",
        en: "Sets the player's base Magicule gain attribute.",
        pt: "Define o atributo base de ganho de Magicule do jogador.",
        fr: "Définit l'attribut de base de gain de Magicule du joueur.",
        de: "Legt das Basis-Magicule-Zuwachsattribut des Spielers fest.",
        it: "Imposta l'attributo base di guadagno di Magicule del giocatore.",
        ru: "Устанавливает базовый атрибут прироста Magicule игрока.",
        ja: "プレイヤーの基礎マジキュル獲得属性を設定します。",
        ko: "플레이어의 기본 마기큘 획득 속성을 설정합니다.",
        zh: "设置玩家的基础魔素获取属性。",
        ar: "يحدد سمة اكتساب Magicule الأساسية للاعب.",
        hi: "खिलाड़ी का बेस मैजिक्यूल गेन एट्रिब्यूट सेट करता है।",
        pl: "Ustawia bazowy atrybut zdobywania Magicule gracza.",
        tr: "Oyuncunun temel Magicule kazanım özniteliğini ayarlar.",
        nl: "Stelt het basis-Magicule-winstattribuut van de speler in."
      } },
      { syntax: "/epgain <jugador> set ap <valor>", desc: {
        es: "Fija el atributo base de ganancia de Aura del jugador.",
        en: "Sets the player's base Aura gain attribute.",
        pt: "Define o atributo base de ganho de Aura do jogador.",
        fr: "Définit l'attribut de base de gain d'Aura du joueur.",
        de: "Legt das Basis-Aura-Zuwachsattribut des Spielers fest.",
        it: "Imposta l'attributo base di guadagno di Aura del giocatore.",
        ru: "Устанавливает базовый атрибут прироста Aura игрока.",
        ja: "プレイヤーの基礎オーラ獲得属性を設定します。",
        ko: "플레이어의 기본 오라 획득 속성을 설정합니다.",
        zh: "设置玩家的基础斗气获取属性。",
        ar: "يحدد سمة اكتساب Aura الأساسية للاعب.",
        hi: "खिलाड़ी का बेस आभा गेन एट्रिब्यूट सेट करता है।",
        pl: "Ustawia bazowy atrybut zdobywania Aury gracza.",
        tr: "Oyuncunun temel Aura kazanım özniteliğini ayarlar.",
        nl: "Stelt het basis-Aura-winstattribuut van de speler in."
      } }
    ]
  },
  {
    id: "mobep",
    root: "/mobep",
    permKey: "op",
    summary: {
      es: "Sobrescribe el EP (Energy Parameter) que otorga un tipo de mob al morir.",
      en: "Overrides the EP (Energy Parameter) a mob type grants on death.",
      pt: "Sobrescreve o EP (Energy Parameter) que um tipo de mob concede ao morrer.",
      fr: "Remplace l'EP (Energy Parameter) accordé par un type de mob à sa mort.",
      de: "Überschreibt den EP (Energy Parameter), den ein Mob-Typ beim Tod gewährt.",
      it: "Sovrascrive l'EP (Energy Parameter) concesso da un tipo di mob alla morte.",
      ru: "Переопределяет EP (Energy Parameter), выдаваемый типом моба при смерти.",
      ja: "モブの種類が死亡時に与えるEP（エネルギーパラメータ）を上書きします。",
      ko: "몹 종류가 죽을 때 부여하는 EP(에너지 파라미터)를 재정의합니다.",
      zh: "覆盖某类生物死亡时授予的 EP（能量参数）。",
      ar: "يتجاوز EP (معامل الطاقة) الذي يمنحه نوع الوحش عند الموت.",
      hi: "एक मॉब टाइप मरने पर जो EP (एनर्जी पैरामीटर) देता है, उसे ओवरराइड करता है।",
      pl: "Nadpisuje EP (Energy Parameter) przyznawany przez typ moba przy śmierci.",
      tr: "Bir mob türünün ölümde verdiği EP'yi (Energy Parameter) geçersiz kılar.",
      nl: "Overschrijft de EP (Energy Parameter) die een mobtype bij overlijden geeft."
    },
    subs: [
      { syntax: "/mobep <entity_type> get", desc: {
        es: "Muestra si ese tipo de mob tiene un EP sobreescrito y cuál es.",
        en: "Shows whether that mob type has an EP override and what it is.",
        pt: "Mostra se esse tipo de mob tem um EP sobrescrito e qual é.",
        fr: "Indique si ce type de mob a un EP remplacé et lequel.",
        de: "Zeigt, ob dieser Mob-Typ einen EP-Override hat und welchen.",
        it: "Mostra se quel tipo di mob ha un EP sovrascritto e quale.",
        ru: "Показывает, есть ли у этого типа моба переопределённый EP и какой.",
        ja: "そのモブ種にEP上書きがあるか、あればその値を表示します。",
        ko: "해당 몹 종류에 EP 재정의가 있는지, 있다면 그 값을 표시합니다.",
        zh: "显示该生物类型是否有覆盖的 EP 值，以及具体是多少。",
        ar: "يعرض ما إذا كان لهذا النوع من الوحوش EP متجاوز وما هو.",
        hi: "दिखाता है कि उस मॉब टाइप का EP ओवरराइड है या नहीं, और क्या है।",
        pl: "Pokazuje, czy dany typ moba ma nadpisany EP i jaki.",
        tr: "O mob türünün geçersiz kılınmış bir EP'si olup olmadığını ve ne olduğunu gösterir.",
        nl: "Toont of dat mobtype een EP-override heeft en wat die is."
      } },
      { syntax: "/mobep <entity_type> set <multiplicador>", desc: {
        es: "Fija el multiplicador de EP para ese tipo de entidad (aplica a mobs spawneados/cargados desde ese momento).",
        en: "Sets the EP multiplier for that entity type (applies to mobs spawned/loaded from then on).",
        pt: "Define o multiplicador de EP para esse tipo de entidade (aplica-se a mobs gerados/carregados a partir daí).",
        fr: "Définit le multiplicateur d'EP pour ce type d'entité (s'applique aux mobs générés/chargés à partir de ce moment).",
        de: "Legt den EP-Multiplikator für diesen Entitätstyp fest (gilt für ab jetzt gespawnte/geladene Mobs).",
        it: "Imposta il moltiplicatore di EP per quel tipo di entità (si applica ai mob generati/caricati da quel momento).",
        ru: "Устанавливает множитель EP для этого типа сущности (применяется к мобам, появившимся/загруженным с этого момента).",
        ja: "そのエンティティタイプのEP倍率を設定します（以降にスポーン／読み込まれるモブに適用）。",
        ko: "해당 엔티티 종류의 EP 배율을 설정합니다 (그 시점 이후 스폰/로드되는 몹에 적용).",
        zh: "设置该实体类型的 EP 倍率（适用于此后生成/加载的生物）。",
        ar: "يحدد مضاعف EP لهذا النوع من الكيانات (يُطبَّق على الوحوش التي تظهر/تُحمَّل منذ تلك اللحظة).",
        hi: "उस एंटिटी टाइप के लिए EP मल्टीप्लायर सेट करता है (उस पल के बाद स्पॉन/लोड हुए मॉब्स पर लागू)।",
        pl: "Ustawia mnożnik EP dla danego typu bytu (dotyczy mobów zespawnowanych/wczytanych od tej chwili).",
        tr: "O varlık türü için EP çarpanını ayarlar (o andan itibaren doğan/yüklenen moblara uygulanır).",
        nl: "Stelt de EP-multiplier voor dat entiteitstype in (geldt voor mobs die vanaf dat moment spawnen/laden)."
      } },
      { syntax: "/mobep <entity_type> reset", desc: {
        es: "Elimina la sobreescritura, volviendo al EP normal del mob.",
        en: "Removes the override, reverting to the mob's normal EP.",
        pt: "Remove a sobrescrita, voltando ao EP normal do mob.",
        fr: "Supprime le remplacement, revenant à l'EP normal du mob.",
        de: "Entfernt den Override und stellt den normalen EP des Mobs wieder her.",
        it: "Rimuove la sovrascrittura, tornando all'EP normale del mob.",
        ru: "Убирает переопределение, возвращая обычный EP моба.",
        ja: "上書きを解除し、モブ本来のEPに戻します。",
        ko: "재정의를 제거하고 몹의 원래 EP로 되돌립니다.",
        zh: "移除覆盖设置，恢复为该生物的正常 EP。",
        ar: "يزيل التجاوز، ويعيده إلى EP الطبيعي للوحش.",
        hi: "ओवरराइड हटाता है, मॉब के सामान्य EP पर लौटाता है।",
        pl: "Usuwa nadpisanie, przywracając normalny EP moba.",
        tr: "Geçersiz kılmayı kaldırır, mobun normal EP'sine döner.",
        nl: "Verwijdert de override en herstelt de normale EP van de mob."
      } }
    ]
  },
  {
    id: "raceoffer",
    root: "/raceoffer",
    permKey: "player",
    summary: {
      es: "Responde a una oferta de cambio/asignación de raza pendiente (por ejemplo, tras una conversión de raza especial).",
      en: "Responds to a pending race change/assignment offer (e.g. after a special race conversion).",
      pt: "Responde a uma oferta pendente de mudança/atribuição de raça (por exemplo, após uma conversão de raça especial).",
      fr: "Répond à une offre de changement/attribution de race en attente (par ex. après une conversion de race spéciale).",
      de: "Beantwortet ein ausstehendes Angebot zum Rassenwechsel/-zuweisung (z. B. nach einer speziellen Rassenumwandlung).",
      it: "Risponde a un'offerta in sospeso di cambio/assegnazione razza (es. dopo una conversione di razza speciale).",
      ru: "Отвечает на ожидающее предложение смены/назначения расы (например, после особого превращения расы).",
      ja: "保留中の種族変更／割り当てオファーに応答します（特殊な種族転換後など）。",
      ko: "대기 중인 종족 변경/할당 제안에 응답합니다 (예: 특수 종족 전환 후).",
      zh: "回应待处理的种族变更/分配提议（例如特殊种族转变后）。",
      ar: "يستجيب لعرض معلّق لتغيير/تعيين العرق (مثلاً بعد تحول عرقي خاص).",
      hi: "लंबित रेस बदलाव/असाइनमेंट ऑफर का जवाब देता है (जैसे किसी विशेष रेस कन्वर्शन के बाद)।",
      pl: "Odpowiada na oczekującą ofertę zmiany/przypisania rasy (np. po specjalnej konwersji rasy).",
      tr: "Bekleyen bir ırk değişikliği/atama teklifine yanıt verir (örn. özel bir ırk dönüşümünden sonra).",
      nl: "Reageert op een openstaand ras-wijzigings-/toewijzingsaanbod (bijv. na een speciale rasomzetting)."
    },
    subs: [
      { syntax: "/raceoffer accept", desc: {
        es: "Acepta la oferta de raza pendiente.",
        en: "Accepts the pending race offer.",
        pt: "Aceita a oferta de raça pendente.",
        fr: "Accepte l'offre de race en attente.",
        de: "Nimmt das ausstehende Rassenangebot an.",
        it: "Accetta l'offerta di razza in sospeso.",
        ru: "Принимает ожидающее предложение расы.",
        ja: "保留中の種族オファーを受け入れます。",
        ko: "대기 중인 종족 제안을 수락합니다.",
        zh: "接受待处理的种族提议。",
        ar: "يقبل عرض العرق المعلّق.",
        hi: "लंबित रेस ऑफर स्वीकार करता है।",
        pl: "Akceptuje oczekującą ofertę rasy.",
        tr: "Bekleyen ırk teklifini kabul eder.",
        nl: "Accepteert het openstaande rasaanbod."
      } },
      { syntax: "/raceoffer reject", desc: {
        es: "Rechaza la oferta pendiente (se pierde).",
        en: "Rejects the pending offer (it's lost).",
        pt: "Rejeita a oferta pendente (ela é perdida).",
        fr: "Refuse l'offre en attente (elle est perdue).",
        de: "Lehnt das ausstehende Angebot ab (es geht verloren).",
        it: "Rifiuta l'offerta in sospeso (viene persa).",
        ru: "Отклоняет ожидающее предложение (оно теряется).",
        ja: "保留中のオファーを拒否します（消滅します）。",
        ko: "대기 중인 제안을 거부합니다 (제안이 사라집니다).",
        zh: "拒绝待处理的提议（提议将消失）。",
        ar: "يرفض العرض المعلّق (يُفقد).",
        hi: "लंबित ऑफर अस्वीकार करता है (यह खो जाता है)।",
        pl: "Odrzuca oczekującą ofertę (przepada).",
        tr: "Bekleyen teklifi reddeder (teklif kaybolur).",
        nl: "Wijst het openstaande aanbod af (het gaat verloren)."
      } }
    ]
  },
  {
    id: "uniqueskillcap",
    root: "/uniqueskillcap",
    permKey: "mixed",
    summary: {
      es: "Controla cuántas Unique Skills puede poseer un jugador simultáneamente, de forma global o por jugador.",
      en: "Controls how many Unique Skills a player can hold at once, globally or per player.",
      pt: "Controla quantas Unique Skills um jogador pode possuir ao mesmo tempo, de forma global ou por jogador.",
      fr: "Contrôle combien d'Unique Skills un joueur peut posséder à la fois, globalement ou par joueur.",
      de: "Steuert, wie viele Unique Skills ein Spieler gleichzeitig besitzen kann, global oder pro Spieler.",
      it: "Controlla quante Unique Skills un giocatore può possedere contemporaneamente, globalmente o per giocatore.",
      ru: "Управляет тем, сколько Unique Skills может одновременно иметь игрок — глобально или индивидуально.",
      ja: "プレイヤーが同時に所持できるユニークスキルの数を、全体またはプレイヤーごとに制御します。",
      ko: "플레이어가 동시에 보유할 수 있는 유니크 스킬 수를 전역 또는 개인별로 제어합니다.",
      zh: "控制玩家同时可拥有的固有技能数量，可全局或按玩家设置。",
      ar: "يتحكم في عدد المهارات الفريدة التي يمكن للاعب امتلاكها في وقت واحد، عالميًا أو لكل لاعب.",
      hi: "नियंत्रित करता है कि एक खिलाड़ी एक साथ कितनी यूनिक स्किल्स रख सकता है, ग्लोबली या प्रति खिलाड़ी।",
      pl: "Kontroluje, ile Unique Skills gracz może posiadać jednocześnie, globalnie lub dla danego gracza.",
      tr: "Bir oyuncunun aynı anda kaç Unique Skill'e sahip olabileceğini, genel veya oyuncu bazında kontrol eder.",
      nl: "Bepaalt hoeveel Unique Skills een speler tegelijk mag bezitten, globaal of per speler."
    },
    subs: [
      { syntax: "/uniqueskillcap get", desc: {
        es: "Muestra el límite global actual de Unique Skills por jugador.",
        en: "Shows the current global limit of Unique Skills per player.",
        pt: "Mostra o limite global atual de Unique Skills por jogador.",
        fr: "Affiche la limite globale actuelle d'Unique Skills par joueur.",
        de: "Zeigt das aktuelle globale Limit an Unique Skills pro Spieler.",
        it: "Mostra l'attuale limite globale di Unique Skills per giocatore.",
        ru: "Показывает текущий глобальный лимит Unique Skills на игрока.",
        ja: "現在のプレイヤーごとのユニークスキル全体上限を表示します。",
        ko: "현재 플레이어당 전역 유니크 스킬 한도를 표시합니다.",
        zh: "显示当前每位玩家的固有技能全局上限。",
        ar: "يعرض الحد الأقصى العالمي الحالي للمهارات الفريدة لكل لاعب.",
        hi: "प्रति खिलाड़ी वर्तमान ग्लोबल यूनिक स्किल सीमा दिखाता है।",
        pl: "Pokazuje aktualny globalny limit Unique Skills na gracza.",
        tr: "Oyuncu başına geçerli genel Unique Skill limitini gösterir.",
        nl: "Toont de huidige globale limiet van Unique Skills per speler."
      } },
      { syntax: "/uniqueskillcap set <cantidad>", desc: {
        es: "(op) Fija el límite global.",
        en: "(op) Sets the global limit.",
        pt: "(op) Define o limite global.",
        fr: "(op) Définit la limite globale.",
        de: "(op) Legt das globale Limit fest.",
        it: "(op) Imposta il limite globale.",
        ru: "(op) Устанавливает глобальный лимит.",
        ja: "(op) 全体の上限を設定します。",
        ko: "(op) 전역 한도를 설정합니다.",
        zh: "(op) 设置全局上限。",
        ar: "(op) يحدد الحد الأقصى العالمي.",
        hi: "(op) ग्लोबल सीमा सेट करता है।",
        pl: "(op) Ustawia limit globalny.",
        tr: "(op) Genel limiti ayarlar.",
        nl: "(op) Stelt de globale limiet in."
      } },
      { syntax: "/uniqueskillcap get <jugador>", desc: {
        es: "Muestra el límite efectivo de ese jugador y cuántas Unique Skills posee.",
        en: "Shows that player's effective limit and how many Unique Skills they own.",
        pt: "Mostra o limite efetivo desse jogador e quantas Unique Skills ele possui.",
        fr: "Affiche la limite effective de ce joueur et combien d'Unique Skills il possède.",
        de: "Zeigt das effektive Limit dieses Spielers und wie viele Unique Skills er besitzt.",
        it: "Mostra il limite effettivo di quel giocatore e quante Unique Skills possiede.",
        ru: "Показывает эффективный лимит этого игрока и сколько Unique Skills у него есть.",
        ja: "そのプレイヤーの実効上限と所持するユニークスキル数を表示します。",
        ko: "해당 플레이어의 실질 한도와 보유한 유니크 스킬 수를 표시합니다.",
        zh: "显示该玩家的实际上限以及其拥有的固有技能数量。",
        ar: "يعرض الحد الفعلي لذلك اللاعب وعدد المهارات الفريدة التي يمتلكها.",
        hi: "उस खिलाड़ी की प्रभावी सीमा और उसके पास कितनी यूनिक स्किल्स हैं, दिखाता है।",
        pl: "Pokazuje efektywny limit danego gracza i ile Unique Skills posiada.",
        tr: "O oyuncunun etkin limitini ve kaç Unique Skill'e sahip olduğunu gösterir.",
        nl: "Toont de effectieve limiet van die speler en hoeveel Unique Skills hij bezit."
      } },
      { syntax: "/uniqueskillcap set <jugador> <cantidad>", desc: {
        es: "(op) Fija un límite personalizado (override) para ese jugador.",
        en: "(op) Sets a personal override limit for that player.",
        pt: "(op) Define um limite personalizado (override) para esse jogador.",
        fr: "(op) Définit une limite personnalisée (override) pour ce joueur.",
        de: "(op) Legt ein persönliches Override-Limit für diesen Spieler fest.",
        it: "(op) Imposta un limite personalizzato (override) per quel giocatore.",
        ru: "(op) Устанавливает персональный лимит (переопределение) для этого игрока.",
        ja: "(op) そのプレイヤー専用の上限（オーバーライド）を設定します。",
        ko: "(op) 해당 플레이어의 개인 재정의 한도를 설정합니다.",
        zh: "(op) 为该玩家设置个人自定义上限（覆盖设置）。",
        ar: "(op) يحدد حدًا شخصيًا مخصصًا لذلك اللاعب.",
        hi: "(op) उस खिलाड़ी के लिए एक व्यक्तिगत ओवरराइड सीमा सेट करता है।",
        pl: "(op) Ustawia spersonalizowany limit (nadpisanie) dla danego gracza.",
        tr: "(op) O oyuncu için kişisel bir geçersiz kılma limiti ayarlar.",
        nl: "(op) Stelt een persoonlijke override-limiet in voor die speler."
      } },
      { syntax: "/uniqueskillcap reset <jugador>", desc: {
        es: "(op) Elimina el override personal, volviendo al límite global.",
        en: "(op) Removes the personal override, reverting to the global limit.",
        pt: "(op) Remove o override pessoal, voltando ao limite global.",
        fr: "(op) Supprime l'override personnel, revenant à la limite globale.",
        de: "(op) Entfernt den persönlichen Override und stellt das globale Limit wieder her.",
        it: "(op) Rimuove l'override personale, tornando al limite globale.",
        ru: "(op) Убирает персональное переопределение, возвращая глобальный лимит.",
        ja: "(op) 個別のオーバーライドを解除し、全体の上限に戻します。",
        ko: "(op) 개인 재정의를 제거하고 전역 한도로 되돌립니다.",
        zh: "(op) 移除个人自定义上限，恢复为全局上限。",
        ar: "(op) يزيل التجاوز الشخصي، ويعيده إلى الحد العالمي.",
        hi: "(op) व्यक्तिगत ओवरराइड हटाता है, ग्लोबल सीमा पर लौटाता है।",
        pl: "(op) Usuwa osobiste nadpisanie, przywracając limit globalny.",
        tr: "(op) Kişisel geçersiz kılmayı kaldırır, genel limite döner.",
        nl: "(op) Verwijdert de persoonlijke override en herstelt de globale limiet."
      } }
    ]
  },
  {
    id: "faction",
    root: "/faction admin",
    permKey: "op",
    summary: {
      es: "Gestiona el tipo de una facción (Organización ↔ Reino/Kingdom).",
      en: "Manages a faction's type (Organization ↔ Kingdom).",
      pt: "Gerencia o tipo de uma facção (Organização ↔ Reino/Kingdom).",
      fr: "Gère le type d'une faction (Organisation ↔ Royaume).",
      de: "Verwaltet den Typ einer Fraktion (Organisation ↔ Königreich).",
      it: "Gestisce il tipo di una fazione (Organizzazione ↔ Regno).",
      ru: "Управляет типом фракции (Организация ↔ Королевство).",
      ja: "派閥の種別（組織↔王国）を管理します。",
      ko: "파벌의 유형(조직 ↔ 왕국)을 관리합니다.",
      zh: "管理一个阵营的类型（组织 ↔ 王国）。",
      ar: "يدير نوع الفصيل (منظمة ↔ مملكة).",
      hi: "एक फ़ैक्शन के प्रकार (ऑर्गेनाइज़ेशन ↔ किंगडम) को प्रबंधित करता है।",
      pl: "Zarządza typem frakcji (Organizacja ↔ Królestwo).",
      tr: "Bir hizibin türünü yönetir (Organizasyon ↔ Krallık).",
      nl: "Beheert het type van een factie (Organisatie ↔ Koninkrijk)."
    },
    subs: [
      { syntax: "/faction admin promote <nombre>", desc: {
        es: "Asciende una facción de nivel 10+ a Kingdom.",
        en: "Promotes a level 10+ faction to Kingdom.",
        pt: "Promove uma facção de nível 10+ a Kingdom.",
        fr: "Promeut une faction de niveau 10+ en Royaume.",
        de: "Befördert eine Fraktion ab Level 10 zum Königreich.",
        it: "Promuove una fazione di livello 10+ a Regno.",
        ru: "Повышает фракцию уровня 10+ до Королевства.",
        ja: "レベル10以上の派閥を王国に昇格させます。",
        ko: "레벨 10 이상의 파벌을 왕국으로 승격시킵니다.",
        zh: "将 10 级以上的阵营晋升为王国。",
        ar: "يرقّي فصيلًا من المستوى 10+ إلى مملكة.",
        hi: "लेवल 10+ फ़ैक्शन को किंगडम में अपग्रेड करता है।",
        pl: "Awansuje frakcję na poziomie 10+ do Królestwa.",
        tr: "Seviye 10+ bir hizibi Krallığa yükseltir.",
        nl: "Bevordert een factie van level 10+ tot Koninkrijk."
      } },
      { syntax: "/faction admin demote <nombre>", desc: {
        es: "Degrada una facción de vuelta a Organización (expulsa miembros que excedan el límite del nuevo tipo).",
        en: "Demotes a faction back to Organization (removes members exceeding the new type's cap).",
        pt: "Rebaixa uma facção de volta a Organização (remove membros que excedam o limite do novo tipo).",
        fr: "Rétrograde une faction en Organisation (exclut les membres dépassant la limite du nouveau type).",
        de: "Stuft eine Fraktion zurück zur Organisation herab (entfernt Mitglieder über dem neuen Limit).",
        it: "Retrocede una fazione a Organizzazione (rimuove i membri che eccedono il limite del nuovo tipo).",
        ru: "Понижает фракцию обратно до Организации (исключает участников сверх лимита нового типа).",
        ja: "派閥を組織に降格させます（新しい種別の上限を超えたメンバーは除名されます）。",
        ko: "파벌을 조직으로 강등시킵니다 (새 유형의 한도를 초과하는 멤버는 추방됩니다).",
        zh: "将阵营降级为组织（超出新类型上限的成员将被移除）。",
        ar: "يخفّض فصيلًا إلى منظمة (يطرد الأعضاء الزائدين عن حد النوع الجديد).",
        hi: "एक फ़ैक्शन को वापस ऑर्गेनाइज़ेशन में डिमोट करता है (नई सीमा से अधिक सदस्य हटाए जाते हैं)।",
        pl: "Degraduje frakcję z powrotem do Organizacji (usuwa członków przekraczających limit nowego typu).",
        tr: "Bir hizibi tekrar Organizasyona düşürür (yeni türün limitini aşan üyeleri çıkarır).",
        nl: "Degradeert een factie terug naar Organisatie (verwijdert leden die de limiet van het nieuwe type overschrijden)."
      } }
    ]
  },
  {
    id: "racespawn",
    root: "/racespawn",
    permKey: "op",
    summary: {
      es: "Prueba y recarga la configuración de spawns de razas específicas por bioma.",
      en: "Tests and reloads the per-biome race spawn configuration.",
      pt: "Testa e recarrega a configuração de spawns de raças específicas por bioma.",
      fr: "Teste et recharge la configuration de spawn des races par biome.",
      de: "Testet und lädt die biomspezifische Rassenspawn-Konfiguration neu.",
      it: "Testa e ricarica la configurazione di spawn delle razze per bioma.",
      ru: "Тестирует и перезагружает конфигурацию появления рас по биомам.",
      ja: "バイオームごとの種族スポーン設定をテスト・再読み込みします。",
      ko: "바이옴별 종족 스폰 설정을 테스트하고 다시 불러옵니다.",
      zh: "测试并重新加载按生物群系设置的种族生成配置。",
      ar: "يختبر ويعيد تحميل إعدادات ظهور الأعراق حسب البيئة الحيوية.",
      hi: "बायोम के अनुसार रेस स्पॉन कॉन्फ़िगरेशन को टेस्ट और रीलोड करता है।",
      pl: "Testuje i przeładowuje konfigurację spawnów ras dla poszczególnych biomów.",
      tr: "Biyom başına ırk doğuş yapılandırmasını test eder ve yeniden yükler.",
      nl: "Test en herlaadt de per-biome rasspawn-configuratie."
    },
    subs: [
      { syntax: "/racespawn test <raza>", desc: {
        es: "Coloca al jugador en un punto de spawn del bioma configurado para esa raza (útil para probar configuraciones).",
        en: "Teleports the player to a configured biome spawn point for that race (useful for testing configs).",
        pt: "Teleporta o jogador para um ponto de spawn do bioma configurado para essa raça (útil para testar configurações).",
        fr: "Téléporte le joueur vers un point de spawn de biome configuré pour cette race (utile pour tester les configs).",
        de: "Teleportiert den Spieler zu einem konfigurierten Biom-Spawnpunkt für diese Rasse (nützlich zum Testen von Konfigurationen).",
        it: "Teletrasporta il giocatore a un punto di spawn del bioma configurato per quella razza (utile per testare le configurazioni).",
        ru: "Телепортирует игрока к настроенной точке появления биома для этой расы (полезно для проверки конфигурации).",
        ja: "そのレースに設定されたバイオームのスポーン地点へプレイヤーをテレポートします（設定テストに便利）。",
        ko: "해당 종족에 설정된 바이옴 스폰 지점으로 플레이어를 텔레포트합니다 (설정 테스트에 유용).",
        zh: "将玩家传送到为该种族配置的生物群系生成点（便于测试配置）。",
        ar: "ينقل اللاعب إلى نقطة ظهور بيئة حيوية مُعدّة لذلك العرق (مفيد لاختبار الإعدادات).",
        hi: "खिलाड़ी को उस रेस के लिए कॉन्फ़िगर किए गए बायोम स्पॉन पॉइंट पर टेलीपोर्ट करता है (कॉन्फ़िग टेस्ट के लिए उपयोगी)।",
        pl: "Teleportuje gracza do skonfigurowanego punktu spawnu biomu dla danej rasy (przydatne do testowania konfiguracji).",
        tr: "Oyuncuyu o ırk için yapılandırılmış bir biyom doğuş noktasına ışınlar (yapılandırmaları test etmek için kullanışlı).",
        nl: "Teleporteert de speler naar een geconfigureerd biome-spawnpunt voor dat ras (handig om configuraties te testen)."
      } },
      { syntax: "/racespawn reload", desc: {
        es: "Recarga el archivo de configuración de race-spawn sin reiniciar el servidor.",
        en: "Reloads the race-spawn config file without restarting the server.",
        pt: "Recarrega o arquivo de configuração de race-spawn sem reiniciar o servidor.",
        fr: "Recharge le fichier de configuration race-spawn sans redémarrer le serveur.",
        de: "Lädt die race-spawn-Konfigurationsdatei neu, ohne den Server neu zu starten.",
        it: "Ricarica il file di configurazione race-spawn senza riavviare il server.",
        ru: "Перезагружает конфигурационный файл race-spawn без перезапуска сервера.",
        ja: "サーバーを再起動せずにrace-spawn設定ファイルを再読み込みします。",
        ko: "서버를 재시작하지 않고 race-spawn 설정 파일을 다시 불러옵니다.",
        zh: "无需重启服务器即可重新加载 race-spawn 配置文件。",
        ar: "يعيد تحميل ملف إعدادات race-spawn دون إعادة تشغيل الخادم.",
        hi: "सर्वर को रीस्टार्ट किए बिना race-spawn कॉन्फ़िग फ़ाइल को रीलोड करता है।",
        pl: "Przeładowuje plik konfiguracyjny race-spawn bez restartowania serwera.",
        tr: "Sunucuyu yeniden başlatmadan race-spawn yapılandırma dosyasını yeniden yükler.",
        nl: "Herlaadt het race-spawn-configuratiebestand zonder de server te herstarten."
      } }
    ]
  },
  {
    id: "reputation",
    root: "/reputation",
    permKey: "player",
    summary: {
      es: "Consulta la reputación de comerciante y la notoriedad de un jugador (sistema de trading).",
      en: "Checks a player's merchant reputation and notoriety (trading system).",
      pt: "Consulta a reputação de comerciante e a notoriedade de um jogador (sistema de trading).",
      fr: "Vérifie la réputation de marchand et la notoriété d'un joueur (système de commerce).",
      de: "Prüft den Händlerruf und die Bekanntheit eines Spielers (Handelssystem).",
      it: "Controlla la reputazione da mercante e la notorietà di un giocatore (sistema di scambio).",
      ru: "Проверяет торговую репутацию и известность игрока (торговая система).",
      ja: "プレイヤーの商人評判と悪名を確認します（取引システム）。",
      ko: "플레이어의 상인 평판과 악명을 확인합니다 (거래 시스템).",
      zh: "查看玩家的商人声望和恶名（交易系统）。",
      ar: "يتحقق من سمعة التاجر وشهرة اللاعب (نظام التجارة).",
      hi: "एक खिलाड़ी की मर्चेंट रेप्युटेशन और नोटोरिएटी जाँचता है (ट्रेडिंग सिस्टम)।",
      pl: "Sprawdza reputację kupiecką i rozgłos gracza (system handlu).",
      tr: "Bir oyuncunun tüccar itibarını ve nam düzeyini kontrol eder (ticaret sistemi).",
      nl: "Controleert de handelaarsreputatie en beruchtheid van een speler (handelssysteem)."
    },
    subs: [
      { syntax: "/reputation [jugador]", desc: {
        es: "Muestra la reputación como comerciante y la notoriedad, propia o de otro jugador.",
        en: "Shows merchant reputation and notoriety, your own or another player's.",
        pt: "Mostra a reputação como comerciante e a notoriedade, própria ou de outro jogador.",
        fr: "Affiche la réputation de marchand et la notoriété, les vôtres ou celles d'un autre joueur.",
        de: "Zeigt Händlerruf und Bekanntheit, deine eigenen oder die eines anderen Spielers.",
        it: "Mostra la reputazione da mercante e la notorietà, tue o di un altro giocatore.",
        ru: "Показывает торговую репутацию и известность — вашу или другого игрока.",
        ja: "自分または他プレイヤーの商人評判と悪名を表示します。",
        ko: "본인 또는 다른 플레이어의 상인 평판과 악명을 표시합니다.",
        zh: "显示你自己或另一名玩家的商人声望和恶名。",
        ar: "يعرض سمعة التاجر والشهرة، الخاصة بك أو بلاعب آخر.",
        hi: "आपकी अपनी या किसी अन्य खिलाड़ी की मर्चेंट रेप्युटेशन और नोटोरिएटी दिखाता है।",
        pl: "Pokazuje reputację kupiecką i rozgłos — twoje lub innego gracza.",
        tr: "Kendi veya başka bir oyuncunun tüccar itibarını ve namını gösterir.",
        nl: "Toont handelaarsreputatie en beruchtheid, van jezelf of van een andere speler."
      } }
    ]
  },
  {
    id: "shops",
    root: "/shops",
    permKey: "player",
    summary: {
      es: "Lista las tiendas (Trade Stalls) registradas en el servidor.",
      en: "Lists the Trade Stalls registered on the server.",
      pt: "Lista as lojas (Trade Stalls) registradas no servidor.",
      fr: "Liste les échoppes (Trade Stalls) enregistrées sur le serveur.",
      de: "Listet die auf dem Server registrierten Handelsstände (Trade Stalls) auf.",
      it: "Elenca le bancarelle (Trade Stalls) registrate sul server.",
      ru: "Показывает список торговых прилавков (Trade Stalls), зарегистрированных на сервере.",
      ja: "サーバーに登録された取引所（Trade Stalls）を一覧表示します。",
      ko: "서버에 등록된 거래소(Trade Stalls) 목록을 표시합니다.",
      zh: "列出服务器上已注册的交易摊位（Trade Stalls）。",
      ar: "يسرد أكشاك التجارة (Trade Stalls) المسجّلة على الخادم.",
      hi: "सर्वर पर पंजीकृत दुकानों (Trade Stalls) की सूची दिखाता है।",
      pl: "Wyświetla listę stoisk handlowych (Trade Stalls) zarejestrowanych na serwerze.",
      tr: "Sunucuda kayıtlı Ticaret Tezgahlarını (Trade Stalls) listeler.",
      nl: "Toont een lijst van geregistreerde handelskraampjes (Trade Stalls) op de server."
    },
    subs: [
      { syntax: "/shops list", desc: {
        es: "Muestra todas las tiendas registradas con nombre, dueño y un enlace clicable para teletransportarte.",
        en: "Shows every registered shop with name, owner, and a clickable teleport link.",
        pt: "Mostra todas as lojas registradas com nome, dono e um link clicável para teletransporte.",
        fr: "Affiche toutes les échoppes enregistrées avec nom, propriétaire et un lien cliquable de téléportation.",
        de: "Zeigt alle registrierten Stände mit Namen, Besitzer und einem klickbaren Teleport-Link.",
        it: "Mostra tutte le bancarelle registrate con nome, proprietario e un link cliccabile per teletrasportarti.",
        ru: "Показывает все зарегистрированные лавки с именем, владельцем и кликабельной ссылкой для телепортации.",
        ja: "登録済みの全店舗を名前・オーナー・クリックでテレポートできるリンク付きで表示します。",
        ko: "이름, 소유자, 클릭 시 텔레포트되는 링크와 함께 등록된 모든 상점을 표시합니다.",
        zh: "显示所有已注册店铺，包含名称、店主和可点击传送的链接。",
        ar: "يعرض جميع المتاجر المسجّلة مع الاسم والمالك ورابط قابل للنقر للانتقال إليه.",
        hi: "नाम, मालिक और क्लिक करने योग्य टेलीपोर्ट लिंक के साथ सभी पंजीकृत दुकानें दिखाता है।",
        pl: "Pokazuje wszystkie zarejestrowane sklepy z nazwą, właścicielem i klikalnym linkiem teleportacji.",
        tr: "Kayıtlı tüm dükkanları isim, sahip ve tıklanabilir ışınlanma bağlantısıyla gösterir.",
        nl: "Toont alle geregistreerde winkels met naam, eigenaar en een klikbare teleportlink."
      } }
    ]
  },
  {
    id: "tradeconfirm",
    root: "/tradeconfirm",
    permKey: "player",
    summary: {
      es: "Confirma o rechaza una compra pendiente en una tienda (Trade Stall) de otro jugador.",
      en: "Confirms or declines a pending purchase at another player's Trade Stall.",
      pt: "Confirma ou recusa uma compra pendente em uma loja (Trade Stall) de outro jogador.",
      fr: "Confirme ou refuse un achat en attente dans l'échoppe d'un autre joueur.",
      de: "Bestätigt oder lehnt einen ausstehenden Kauf an einem Handelsstand eines anderen Spielers ab.",
      it: "Conferma o rifiuta un acquisto in sospeso alla bancarella di un altro giocatore.",
      ru: "Подтверждает или отклоняет ожидающую покупку в лавке другого игрока.",
      ja: "他プレイヤーの取引所での保留中の購入を確定または拒否します。",
      ko: "다른 플레이어의 거래소에서 대기 중인 구매를 확정하거나 거부합니다.",
      zh: "确认或拒绝在另一玩家摊位的待处理购买。",
      ar: "يؤكد أو يرفض عملية شراء معلّقة في كشك تجارة لاعب آخر.",
      hi: "किसी अन्य खिलाड़ी की दुकान पर लंबित खरीद की पुष्टि या अस्वीकार करता है।",
      pl: "Potwierdza lub odrzuca oczekujący zakup w stoisku innego gracza.",
      tr: "Başka bir oyuncunun Ticaret Tezgahındaki bekleyen bir satın almayı onaylar veya reddeder.",
      nl: "Bevestigt of weigert een openstaande aankoop bij het handelskraampje van een andere speler."
    },
    subs: [
      { syntax: "/tradeconfirm accept", desc: {
        es: "Confirma la compra pendiente.",
        en: "Confirms the pending purchase.",
        pt: "Confirma a compra pendente.",
        fr: "Confirme l'achat en attente.",
        de: "Bestätigt den ausstehenden Kauf.",
        it: "Conferma l'acquisto in sospeso.",
        ru: "Подтверждает ожидающую покупку.",
        ja: "保留中の購入を確定します。",
        ko: "대기 중인 구매를 확정합니다.",
        zh: "确认待处理的购买。",
        ar: "يؤكد عملية الشراء المعلّقة.",
        hi: "लंबित खरीद की पुष्टि करता है।",
        pl: "Potwierdza oczekujący zakup.",
        tr: "Bekleyen satın almayı onaylar.",
        nl: "Bevestigt de openstaande aankoop."
      } },
      { syntax: "/tradeconfirm decline", desc: {
        es: "Rechaza la compra pendiente.",
        en: "Declines the pending purchase.",
        pt: "Recusa a compra pendente.",
        fr: "Refuse l'achat en attente.",
        de: "Lehnt den ausstehenden Kauf ab.",
        it: "Rifiuta l'acquisto in sospeso.",
        ru: "Отклоняет ожидающую покупку.",
        ja: "保留中の購入を拒否します。",
        ko: "대기 중인 구매를 거부합니다.",
        zh: "拒绝待处理的购买。",
        ar: "يرفض عملية الشراء المعلّقة.",
        hi: "लंबित खरीद अस्वीकार करता है।",
        pl: "Odrzuca oczekujący zakup.",
        tr: "Bekleyen satın almayı reddeder.",
        nl: "Weigert de openstaande aankoop."
      } }
    ]
  },
  {
    id: "mpregg",
    root: "/mpregg",
    permKey: "player",
    summary: {
      es: "Responde a una solicitud de 'impregnación' de la Unique Skill Mpregg.",
      en: "Responds to an 'impregnation' request from the Mpregg Unique Skill.",
      pt: "Responde a um pedido de 'impregnação' da Unique Skill Mpregg.",
      fr: "Répond à une demande d'« imprégnation » de l'Unique Skill Mpregg.",
      de: "Beantwortet eine „Schwängerungs“-Anfrage der Unique Skill Mpregg.",
      it: "Risponde a una richiesta di 'gravidanza' della Unique Skill Mpregg.",
      ru: "Отвечает на запрос «оплодотворения» от Unique Skill Mpregg.",
      ja: "ユニークスキル「Mpregg」の「妊娠」リクエストに応答します。",
      ko: "유니크 스킬 Mpregg의 '임신' 요청에 응답합니다.",
      zh: "回应来自固有技能 Mpregg 的“怀孕”请求。",
      ar: "يستجيب لطلب 'الحمل' من المهارة الفريدة Mpregg.",
      hi: "यूनिक स्किल Mpregg के 'इम्प्रेग्नेशन' अनुरोध का जवाब देता है।",
      pl: "Odpowiada na prośbę o 'zapłodnienie' z Unique Skill Mpregg.",
      tr: "Mpregg Unique Skill'inden gelen 'gebe bırakma' isteğine yanıt verir.",
      nl: "Reageert op een 'bevruchtings'-verzoek van de Unique Skill Mpregg."
    },
    subs: [
      { syntax: "/mpregg accept", desc: {
        es: "Acepta la solicitud pendiente.",
        en: "Accepts the pending request.",
        pt: "Aceita o pedido pendente.",
        fr: "Accepte la demande en attente.",
        de: "Nimmt die ausstehende Anfrage an.",
        it: "Accetta la richiesta in sospeso.",
        ru: "Принимает ожидающий запрос.",
        ja: "保留中のリクエストを受け入れます。",
        ko: "대기 중인 요청을 수락합니다.",
        zh: "接受待处理的请求。",
        ar: "يقبل الطلب المعلّق.",
        hi: "लंबित अनुरोध स्वीकार करता है।",
        pl: "Akceptuje oczekującą prośbę.",
        tr: "Bekleyen isteği kabul eder.",
        nl: "Accepteert het openstaande verzoek."
      } },
      { syntax: "/mpregg decline", desc: {
        es: "Rechaza la solicitud pendiente.",
        en: "Declines the pending request.",
        pt: "Recusa o pedido pendente.",
        fr: "Refuse la demande en attente.",
        de: "Lehnt die ausstehende Anfrage ab.",
        it: "Rifiuta la richiesta in sospeso.",
        ru: "Отклоняет ожидающий запрос.",
        ja: "保留中のリクエストを拒否します。",
        ko: "대기 중인 요청을 거부합니다.",
        zh: "拒绝待处理的请求。",
        ar: "يرفض الطلب المعلّق.",
        hi: "लंबित अनुरोध अस्वीकार करता है।",
        pl: "Odrzuca oczekującą prośbę.",
        tr: "Bekleyen isteği reddeder.",
        nl: "Weigert het openstaande verzoek."
      } }
    ]
  },
  {
    id: "bounty",
    root: "/bounty",
    permKey: "mixed",
    summary: {
      es: "Sistema de recompensas de la Unique Skill Star Detective: pon precio a la cabeza de otro jugador.",
      en: "The Star Detective Unique Skill's bounty system: put a price on another player's head.",
      pt: "Sistema de recompensas da Unique Skill Star Detective: coloque um preço na cabeça de outro jogador.",
      fr: "Système de primes de l'Unique Skill Star Detective : mettez à prix la tête d'un autre joueur.",
      de: "Das Kopfgeldsystem der Unique Skill Star Detective: setze ein Kopfgeld auf einen anderen Spieler.",
      it: "Il sistema di taglie della Unique Skill Star Detective: metti una taglia sulla testa di un altro giocatore.",
      ru: "Система наград Unique Skill Star Detective: назначьте награду за голову другого игрока.",
      ja: "ユニークスキル「Star Detective」の賞金システム：他プレイヤーの首に賞金をかけます。",
      ko: "유니크 스킬 Star Detective의 현상금 시스템: 다른 플레이어의 목에 현상금을 겁니다.",
      zh: "固有技能 Star Detective 的悬赏系统：为另一名玩家的人头悬赏。",
      ar: "نظام المكافآت الخاص بالمهارة الفريدة Star Detective: ضع مكافأة على رأس لاعب آخر.",
      hi: "यूनिक स्किल Star Detective का बाउंटी सिस्टम: किसी अन्य खिलाड़ी के सिर पर इनाम रखें।",
      pl: "System nagród Unique Skill Star Detective: wyznacz nagrodę za głowę innego gracza.",
      tr: "Star Detective Unique Skill'inin ödül sistemi: başka bir oyuncunun kellesine ödül koy.",
      nl: "Het premiesysteem van de Unique Skill Star Detective: zet een prijs op het hoofd van een andere speler."
    },
    subs: [
      { syntax: "/bounty place <jugador>", desc: {
        es: "Inicia el proceso para poner una recompensa sobre un jugador (abre un cofre de depósito).",
        en: "Starts placing a bounty on a player (opens a deposit chest).",
        pt: "Inicia o processo para colocar uma recompensa sobre um jogador (abre um baú de depósito).",
        fr: "Démarre le processus pour mettre une prime sur un joueur (ouvre un coffre de dépôt).",
        de: "Startet das Setzen eines Kopfgelds auf einen Spieler (öffnet eine Einzahlungskiste).",
        it: "Avvia il processo per mettere una taglia su un giocatore (apre una cassa di deposito).",
        ru: "Начинает назначение награды за игрока (открывает сундук для внесения средств).",
        ja: "プレイヤーへの賞金設定を開始します（預け入れ用チェストが開きます）。",
        ko: "플레이어에게 현상금을 거는 과정을 시작합니다 (예치용 상자가 열립니다).",
        zh: "开始为玩家设置悬赏（打开一个存款箱）。",
        ar: "يبدأ عملية وضع مكافأة على لاعب (يفتح صندوق إيداع).",
        hi: "किसी खिलाड़ी पर इनाम रखने की प्रक्रिया शुरू करता है (एक डिपॉज़िट चेस्ट खुलता है)।",
        pl: "Rozpoczyna proces wyznaczania nagrody za gracza (otwiera skrzynię depozytową).",
        tr: "Bir oyuncuya ödül koyma sürecini başlatır (bir depozito sandığı açar).",
        nl: "Start het plaatsen van een premie op een speler (opent een stortkist)."
      } },
      { syntax: "/bounty confirm", desc: {
        es: "Confirma el depósito de la recompensa.",
        en: "Confirms the bounty deposit.",
        pt: "Confirma o depósito da recompensa.",
        fr: "Confirme le dépôt de la prime.",
        de: "Bestätigt die Kopfgeld-Einzahlung.",
        it: "Conferma il deposito della taglia.",
        ru: "Подтверждает внесение награды.",
        ja: "賞金の預け入れを確定します。",
        ko: "현상금 예치를 확정합니다.",
        zh: "确认悬赏存款。",
        ar: "يؤكد إيداع المكافأة.",
        hi: "इनाम जमा की पुष्टि करता है।",
        pl: "Potwierdza depozyt nagrody.",
        tr: "Ödül depozitosunu onaylar.",
        nl: "Bevestigt de premiestorting."
      } },
      { syntax: "/bounty cancel", desc: {
        es: "Cancela la recompensa pendiente.",
        en: "Cancels the pending bounty.",
        pt: "Cancela a recompensa pendente.",
        fr: "Annule la prime en attente.",
        de: "Storniert das ausstehende Kopfgeld.",
        it: "Annulla la taglia in sospeso.",
        ru: "Отменяет ожидающую награду.",
        ja: "保留中の賞金設定をキャンセルします。",
        ko: "대기 중인 현상금을 취소합니다.",
        zh: "取消待处理的悬赏。",
        ar: "يلغي المكافأة المعلّقة.",
        hi: "लंबित इनाम रद्द करता है।",
        pl: "Anuluje oczekującą nagrodę.",
        tr: "Bekleyen ödülü iptal eder.",
        nl: "Annuleert de openstaande premie."
      } },
      { syntax: "/bounty list", desc: {
        es: "Lista las recompensas activas.",
        en: "Lists active bounties.",
        pt: "Lista as recompensas ativas.",
        fr: "Liste les primes actives.",
        de: "Listet aktive Kopfgelder auf.",
        it: "Elenca le taglie attive.",
        ru: "Показывает список активных наград.",
        ja: "有効な賞金一覧を表示します。",
        ko: "활성 현상금 목록을 표시합니다.",
        zh: "列出当前有效的悬赏。",
        ar: "يسرد المكافآت النشطة.",
        hi: "सक्रिय इनामों की सूची दिखाता है।",
        pl: "Wyświetla listę aktywnych nagród.",
        tr: "Aktif ödülleri listeler.",
        nl: "Toont een lijst van actieve premies."
      } },
      { syntax: "/bounty rep get <jugador>", desc: {
        es: "Consulta la reputación de recompensas (bounty rep) de un jugador.",
        en: "Checks a player's bounty reputation.",
        pt: "Consulta a reputação de recompensas (bounty rep) de um jogador.",
        fr: "Vérifie la réputation de primes (bounty rep) d'un joueur.",
        de: "Prüft den Kopfgeld-Ruf (bounty rep) eines Spielers.",
        it: "Controlla la reputazione da taglie (bounty rep) di un giocatore.",
        ru: "Проверяет репутацию по наградам (bounty rep) игрока.",
        ja: "プレイヤーの賞金評判（bounty rep）を確認します。",
        ko: "플레이어의 현상금 평판(bounty rep)을 확인합니다.",
        zh: "查询玩家的悬赏声望（bounty rep）。",
        ar: "يتحقق من سمعة المكافآت (bounty rep) للاعب.",
        hi: "एक खिलाड़ी की बाउंटी रेप्युटेशन (bounty rep) जाँचता है।",
        pl: "Sprawdza reputację nagród (bounty rep) gracza.",
        tr: "Bir oyuncunun ödül itibarını (bounty rep) kontrol eder.",
        nl: "Controleert de premiereputatie (bounty rep) van een speler."
      } },
      { syntax: "/bounty rep set <jugador> <cantidad>", desc: {
        es: "(op) Fija la reputación de recompensas de un jugador.",
        en: "(op) Sets a player's bounty reputation.",
        pt: "(op) Define a reputação de recompensas de um jogador.",
        fr: "(op) Définit la réputation de primes d'un joueur.",
        de: "(op) Legt den Kopfgeld-Ruf eines Spielers fest.",
        it: "(op) Imposta la reputazione da taglie di un giocatore.",
        ru: "(op) Устанавливает репутацию по наградам у игрока.",
        ja: "(op) プレイヤーの賞金評判を設定します。",
        ko: "(op) 플레이어의 현상금 평판을 설정합니다.",
        zh: "(op) 设置玩家的悬赏声望。",
        ar: "(op) يحدد سمعة المكافآت للاعب.",
        hi: "(op) एक खिलाड़ी की बाउंटी रेप्युटेशन सेट करता है।",
        pl: "(op) Ustawia reputację nagród gracza.",
        tr: "(op) Bir oyuncunun ödül itibarını ayarlar.",
        nl: "(op) Stelt de premiereputatie van een speler in."
      } },
      { syntax: "/bounty rep add <jugador> <cantidad>", desc: {
        es: "(op) Suma reputación de recompensas a un jugador.",
        en: "(op) Adds bounty reputation to a player.",
        pt: "(op) Adiciona reputação de recompensas a um jogador.",
        fr: "(op) Ajoute de la réputation de primes à un joueur.",
        de: "(op) Fügt einem Spieler Kopfgeld-Ruf hinzu.",
        it: "(op) Aggiunge reputazione da taglie a un giocatore.",
        ru: "(op) Добавляет игроку репутацию по наградам.",
        ja: "(op) プレイヤーに賞金評判を加算します。",
        ko: "(op) 플레이어에게 현상금 평판을 추가합니다.",
        zh: "(op) 为玩家增加悬赏声望。",
        ar: "(op) يضيف سمعة مكافآت للاعب.",
        hi: "(op) एक खिलाड़ी में बाउंटी रेप्युटेशन जोड़ता है।",
        pl: "(op) Dodaje reputację nagród graczowi.",
        tr: "(op) Bir oyuncuya ödül itibarı ekler.",
        nl: "(op) Voegt premiereputatie toe aan een speler."
      } }
    ]
  }
];
