// Per-language translations for skill / intrinsic content (descHtml, excerpt,
// evolution, race). English lives in skills-data.js / intrinsic-data.js and is
// used as the fallback; anything missing here falls back to English via loc().
// Structure: CONTENT_I18N[type][id][field][langCode] = "translated string".
// Ability names, status-effect names and stat abbreviations (MP, AP, HP, CD, EP)
// are kept in English on purpose so they match the in-game text.
const CONTENT_I18N = {
  skills: {
    anathema: {
      excerpt: { es: "El magícula te dio la espalda, así que convertiste ese rechazo en un arma. Donde otros tejen hechizos, tú los cortas." },
      descHtml: { es: `<span style="color:#FFAA00">Anathema</span><br><span style="color:#AAAAAA">El magícula te dio la espalda, así que convertiste ese rechazo en un arma. Donde otros tejen hechizos, tú los cortas.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Passive] Magicule's Disdain</span>: esta maldición te acompaña tengas la skill equipada o no. Tu ganancia de magícula se reduce un 75%, tu crecimiento general (ganancia de EP) baja un 20% (debes entrenar mucho más que los demás), toda magia que causas golpea al 35% de su poder y recibes un 20% más de daño mágico.<br><span style="color:#55FFFF">[In Slot] Hollow Vessel</span>: un cuerpo que no necesita magia. Ganas Strengthen permanente, 10% más de daño físico y de battlewill, ataques algo más rápidos e inmunidad a que sellen tus skills.<br><span style="color:#55FFFF">[In Slot] Severing Instinct</span>: 25% de probabilidad en cualquier golpe físico o de battlewill (puños o armas) de cortar al objetivo, quitándole sus buffs y sellando sus skills con Anti-Skill.<br><span style="color:#55FFFF">[Toggle] Unshackled</span>: Strengthen II, Resistance y mejores reflejos. Cuesta 100 de aura por segundo.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Antimagic Cleave </span><span style="color:#AAAAAA">(Press)</span>: un golpe perforante a un objetivo a menos de 6 bloques que ignora barreras y resistencias y lo corta. <span style="color:#AAAAAA">400 aura, 10s CD</span><br><span style="color:#FFFF55">[Mode 2] Null Field </span><span style="color:#AAAAAA">(Press)</span>: no causa daño. Un pulso que corta a la vez a todo enemigo en 8 bloques, quitándole sus buffs y sellando sus skills. <span style="color:#AAAAAA">500 aura, 25s CD</span>` }
    },
    courage_oath: {
      excerpt: { es: "Un juramento sellado con sangre y sacrificio. Quien lo porta lucha por defender una ley escrita en el lenguaje de la pérdida." },
      evolution: { es: "Se convierte en Tyr, señor del sacrificio" },
      descHtml: { es: `<span style="color:#FFAA00">Courage Oath</span><br><span style="color:#AAAAAA">Un juramento sellado con sangre y sacrificio. Quien lo porta lucha por defender una ley escrita en el lenguaje de la pérdida.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Martyr's Resolve</span>: +5% de daño por cada 10% de HP que te falte, hasta +50%. Se duplica por debajo del 20% de HP.<br><span style="color:#55FFFF">[Toggle] Unyielding</span>: Resistance I permanente e inmunidad total a Slowness y Burden. Cuesta 100 MP/s.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Oath Strike </span><span style="color:#AAAAAA">(Hold)</span>: concentra 1,5 s y golpea por el 25% del HP actual del objetivo, perforando barreras, resistencias y anulaciones. No se puede usar con el HP lleno. <span style="color:#AAAAAA">5000 MP, 40s CD</span><br><span style="color:#FFFF55">[Mode 2] War Decree </span><span style="color:#AAAAAA">(Press)</span>: Weakness II y Fragility II durante 15 s a un objetivo a menos de 20 bloques. <span style="color:#AAAAAA">3000 MP, 60s CD</span><br><span style="color:#FFFF55">[Mode 3] Condemning Slash </span><span style="color:#AAAAAA">(Press)</span>: una amplia onda de luz por 70 de daño de luz. <span style="color:#AAAAAA">2000 MP, 15s CD</span>` }
    },
    dragon_hoard: {
      excerpt: { es: "La codicia de un dragón cristalizada en poder. Cada muerte alimenta el hambre, y la fuerza que le sigue no tiene fin." },
      evolution: { es: "Se convierte en Fafnir, señor de la codicia" },
      descHtml: { es: `<span style="color:#FFAA00">Dragon's Hoard</span><br><span style="color:#AAAAAA">La codicia de un dragón cristalizada en poder. Cada muerte alimenta el hambre, y la fuerza que le sigue no tiene fin.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Fafnir's Greed</span>: cada muerte suma +2 de HP máx., hasta +300 en total (se reinicia al morir). 15% de probabilidad en un golpe físico de drenar 200 MP del objetivo.<br><span style="color:#55FFFF">[Toggle] Draconic Resilience</span>: el daño recibido se reduce hasta un 25%, escalando con tu reserva total de MP.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Breath of Ruin </span><span style="color:#AAAAAA">(Hold)</span>: lanza a través de un círculo de fuego y exhala un aliento dracónico púrpura por 40 de daño (no deja fuego en el suelo). <span style="color:#AAAAAA">80 MP/tick, 15s CD</span><br><span style="color:#FFFF55">[Mode 2] Hoard's Curse </span><span style="color:#AAAAAA">(Press)</span>: drena 10.000 MP de un objetivo y aplica Energy Blockade II. <span style="color:#AAAAAA">6000 MP, 90s CD</span><br><span style="color:#FFFF55">[Mode 3] Draconic Meteor </span><span style="color:#AAAAAA">(Press)</span>: arroja una Fusion Flare que estalla en un campo ardiente por 70 de daño de fuego. <span style="color:#AAAAAA">4000 MP, 20s CD</span>` }
    },
    equivalence: {
      excerpt: { es: "Para obtener algo, hay que perder algo de igual valor. Quien lo porta pagó el precio hace tiempo, y el mundo mismo es ahora arcilla en sus manos." },
      descHtml: { es: `<span style="color:#FFAA00">Equivalence</span><br><span style="color:#AAAAAA">Para obtener algo, hay que perder algo de igual valor. Quien lo porta pagó el precio hace tiempo, y el mundo mismo es ahora arcilla en sus manos.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Deconstruction</span>: 20% de probabilidad en un golpe físico de descomponer al objetivo, quitándole un efecto beneficioso y aplicando Fragility I.<br><span style="color:#55FFFF">[Owned] Automail</span>: tu brazo derecho y tu pierna izquierda son metal vivo. Todos pueden verlos.<br><span style="color:#55FFFF">[Toggle] Truth's Toll</span>: una palmada sustituye cualquier cántico (Chant Annulment completo, casteo más rápido), Analytical Appraisal, inmunidad a Blindness y el automail se endurece para +5 de armadura. El precio se cobra de tu carne: -5% de HP máx.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Earthen Lance </span><span style="color:#AAAAAA">(Press)</span>: das una palmada y una hilera veloz de enormes púas de tierra brota del suelo frente a ti, 60 de daño de tierra cada una. <span style="color:#AAAAAA">1500 MP, 12s CD</span><br><span style="color:#FFFF55">[Mode 2] Bastion Wall </span><span style="color:#AAAAAA">(Press)</span>: das una palmada y un muro de espeleotema de 5x3 se transmuta del suelo frente a ti. Se desmorona tras 12 segundos y no suelta nada. <span style="color:#AAAAAA">1000 MP, 20s CD</span><br><span style="color:#FFFF55">[Mode 3] Carbon Blade </span><span style="color:#AAAAAA">(Press)</span>: transmuta tu brazo de automail en una hoja visible durante 15 segundos: +5 de daño físico extra (+10 al dominarla), con chispas alquímicas y un tañido metálico en cada golpe. <span style="color:#AAAAAA">2500 MP, 35s CD</span><br><span style="color:#FFFF55">[Mode 4] One is All </span><span style="color:#AAAAAA">(Press, requiere dominio)</span>: ofrece el 30% de tu HP máx. durante 30 segundos: cada ataque perfora resistencias y anulaciones, los ataques físicos ignoran la mitad de todas las esquivas, y la magia y las habilidades de esta skill causan x1,5 de daño. Al terminar el intercambio, la carne es devuelta. <span style="color:#AAAAAA">5000 MP, 120s CD</span>` }
    },
    gjallarhorn_call: {
      excerpt: { es: "Un cuerno cuyo eco anuncia el fin de todas las eras. Siempre vigilante sobre el puente del arcoíris." },
      evolution: { es: "Se convierte en Heimdall, señor del puente" },
      descHtml: { es: `<span style="color:#FFAA00">Gjallarhorn's Call</span><br><span style="color:#AAAAAA">Un cuerno cuyo eco anuncia el fin de todas las eras. Siempre vigilante sobre el puente del arcoíris.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Sentinel's Watch</span>: inmune a Fear, Blindness y Flashed Blindness. Analytical Appraisal activo mientras esté equipada.<br><span style="color:#55FFFF">[Toggle] Rainbow Bridge</span>: +20% de esquiva a cuerpo a cuerpo y a proyectiles, además de inmunidad a Confusion y True Blindness. Cuesta 100 MP/s.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Horn's Warning </span><span style="color:#AAAAAA">(Press)</span>: un estruendo atronador; todo aliado en 40 bloques gana Strengthen y Protection durante 30 s. <span style="color:#AAAAAA">2500 MP, 60s CD</span><br><span style="color:#FFFF55">[Mode 2] Bifrost Beam </span><span style="color:#AAAAAA">(Hold)</span>: un círculo sagrado carga 1 s (0,4 s al dominarla) y dispara un rayo espacial perforante por 45 de daño, envuelto en luz de arcoíris. <span style="color:#AAAAAA">~1500 MP + 400 MP/s, 12s CD</span><br><span style="color:#FFFF55">[Mode 3] Rainbow Strike </span><span style="color:#AAAAAA">(Press)</span>: una bala sagrada veloz por 80 de daño y Blindness. <span style="color:#AAAAAA">2000 MP, 15s CD</span>` }
    },
    gleaming_aura: {
      excerpt: { es: "Un resplandor imperecedero que parece repeler todo daño. Amado por la luz, intacto ante la oscuridad." },
      evolution: { es: "Se convierte en Baldur, señor del resplandor" },
      descHtml: { es: `<span style="color:#FFAA00">Gleaming Aura</span><br><span style="color:#AAAAAA">Un resplandor imperecedero que parece repeler todo daño. Amado por la luz, intacto ante la oscuridad.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Radiant Presence</span>: cada golpe físico causa +15% de su daño como sagrado. El daño sagrado y de luz que causas aumenta un 50%. Inmune a Blindness.<br><span style="color:#55FFFF">[Toggle] Aura of the Sun</span>: los ataques de cualquier cosa con menos EP que tú se anulan por completo (8 MP por punto bloqueado), y el atacante se quema por el 30% de lo bloqueado. El daño que perfora barreras sigue pasando. 5% de probabilidad por tick de aplicar Blind a enemigos en 10 bloques.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Solar Burst </span><span style="color:#AAAAAA">(Press)</span>: una nova sagrada por 80 de daño en 12 bloques que quita un buff a cada enemigo. <span style="color:#AAAAAA">5000 MP, 45s CD</span><br><span style="color:#FFFF55">[Mode 2] Gleam </span><span style="color:#AAAAAA">(Hold)</span>: arde con un aura dorada sagrada que atemoriza a los enemigos más débiles y quema todo en 8 bloques por 15 de daño sagrado por segundo. <span style="color:#AAAAAA">50 MP/tick, 10s CD</span><br><span style="color:#FFFF55">[Mode 3] Solar Beam </span><span style="color:#AAAAAA">(Hold)</span>: un círculo de luz carga 1,5 s (0,5 s al dominarla) y dispara un haz sostenido por 25 de daño con 30 bloques de alcance. <span style="color:#AAAAAA">~1000 MP + 300 MP/s, 12s CD</span>` }
    },
    jotunn_body: {
      excerpt: { es: "La enormidad helada del primer gigante, cuyo cuerpo se convirtió en el mundo. Aquí el tamaño es una inevitabilidad tallada en hielo." },
      evolution: { es: "Se convierte en Ymir, señor de la creación" },
      descHtml: { es: `<span style="color:#FFAA00">Jotunn's Body</span><br><span style="color:#AAAAAA">La enormidad helada del primer gigante, cuyo cuerpo se convirtió en el mundo. Aquí el tamaño es una inevitabilidad tallada en hielo.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Frozen Shell</span>: el daño físico recibido se reduce un 20%. Los atacantes reciben 10 de daño de hielo de vuelta, y los jugadores que te golpean reciben Energy Blockade IV. Inmune al daño de agua.<br><span style="color:#55FFFF">[In slot] Ice Amplifier</span>: el daño de hielo y agua que causas aumenta un 50% mientras Frost Colossus esté activo.<br><span style="color:#55FFFF">[Toggle] Frost Colossus</span>: aumenta tu tamaño, resistencia al empuje, empuje causado, ataque y armadura, con Strength I constante y nieve arremolinada.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Amplify Frost </span><span style="color:#AAAAAA">(Press)</span>: mientras Frost Colossus esté activo, duplica todos sus buffs durante 2 minutos. Agacharse + pulsar lo cancela antes (el cooldown se mantiene). <span style="color:#AAAAAA">400 MP, 120s CD</span><br><span style="color:#FFFF55">[Mode 2] Glaciate </span><span style="color:#AAAAAA">(Hold)</span>: irradia un frío gélido en 10 bloques, aumentando hasta 100 de daño de hielo más Slowness. <span style="color:#AAAAAA">100 MP/tick, 30s CD</span><br><span style="color:#FFFF55">[Mode 3] Frost Pulse </span><span style="color:#AAAAAA">(Press)</span>: una onda de hielo instantánea por 50 de daño y Slowness III en 12 bloques. <span style="color:#AAAAAA">3000 MP, 20s CD</span>` }
    },
    one_eyed_wisdom: {
      excerpt: { es: "Conocimiento comprado al precio de un ojo y una eternidad de vagar. Quien lo porta ve lo que otros no pueden." },
      evolution: { es: "Se convierte en Odín, señor de la sabiduría" },
      descHtml: { es: `<span style="color:#FFAA00">One-Eyed Wisdom</span><br><span style="color:#AAAAAA">Conocimiento comprado al precio de un ojo y una eternidad de vagar. Quien lo porta ve lo que otros no pueden.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Raven's Eye</span>: Analytical Appraisal más Presence Sense (el Eye of Truth), e inmunidad a Blindness, Nausea y Darkness.<br><span style="color:#55FFFF">[Always] Allfather's Lore</span>: +3 puntos de aprendizaje de habilidades; las skills equipadas se aprenden y dominan más rápido.<br><span style="color:#55FFFF">[Always] Foresight</span>: +25% de probabilidad de esquivar automáticamente ataques a cuerpo a cuerpo y proyectiles.<br><span style="color:#55FFFF">[Toggle] Runic Insight</span>: Haste I y Night Vision.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Allfather's Insight </span><span style="color:#AAAAAA">(Press, carga 1,5s)</span>: entra en un estado exaltado durante 30 s: Strength II, Resistance II, Speed II, Regeneration II y Haste II, con una breve Slowness después. <span style="color:#AAAAAA">3000 MP, 70s CD</span><br><span style="color:#FFFF55">[Mode 2] Wisdom's Price </span><span style="color:#AAAAAA">(Press)</span>: sacrifica el 50% del HP actual y el 15% de tu MP máximo de forma permanente para otorgar +50 de dominio a todas las demás skills equipadas. Deja Slowness II y Weakness durante 30 s. <span style="color:#AAAAAA">5000 MP, 180s CD</span><br><span style="color:#FFFF55">[Mode 3] Runic Lance </span><span style="color:#AAAAAA">(Hold)</span>: carga un círculo de rayo (1 s) y arroja una lanza de trueno por 80 de daño. <span style="color:#AAAAAA">1500 MP, 10s CD</span>` }
    },
    ragnaroks_herald: {
      excerpt: { es: "Este poder está sellado y quien lo porta, maldito con debilidad. Para despertarlo hay que dominar la skill y cobrar la vida de nueve jugadores, uno por cada uno de los Nueve Reinos." },
      evolution: { es: "Se convierte en Surtr, señor del Ragnarök (también requiere matar a 9 jugadores)" },
      descHtml: { es: `<span style="color:#FFAA00">Ragnarok's Herald</span><br><span style="color:#AAAAAA">Este poder está sellado y quien lo porta, maldito con debilidad. Para despertarlo hay que dominar la skill y cobrar la vida de nueve jugadores, uno por cada uno de los Nueve Reinos.</span><br><br><span style="font-weight:bold">Latente</span><br>Todo el daño físico que causas se reduce un 30%. Matar jugadores otorga dominio; abatir a 9 jugadores ya con la skill dominada la despierta de forma permanente.<br><br><span style="font-weight:bold">Pasiva (Despierta)</span><br><span style="color:#55FFFF">[Always] Inevitable End</span>: daño físico y de battlewill x2, con +20% de cada golpe físico añadido como daño de fuego.<br><span style="color:#55FFFF">[Always] Fate's Inevitability</span>: cada golpe aplica brevemente Fragility I y Weakness I. Los ataques ignoran resistencias y anulaciones. Siempre tienes Strength I y Fire Resistance.<br><br><span style="font-weight:bold">Activa (Despierta)</span><br><span style="color:#FFFF55">[Mode 1] Surtr's Cleave </span><span style="color:#AAAAAA">(Press)</span>: una enorme onda de hoja ardiente por 3x el daño de tu arma como fuego, incendiando objetivos y aplicando Black Burn. <span style="color:#AAAAAA">4000 AP, 30s CD</span><br><span style="color:#FFFF55">[Mode 2] Surtr's Charge </span><span style="color:#AAAAAA">(Press)</span>: embiste hacia adelante por 90 de daño de fuego, incendiando objetivos y aplicando Slowness II. <span style="color:#AAAAAA">500 AP, 15s CD</span><br><span style="color:#FFFF55">[Mode 3] Inferno Release </span><span style="color:#AAAAAA">(Hold)</span>: lanza un círculo de fuego y un aliento de llamas continuo por 45 de daño. <span style="color:#AAAAAA">80 AP, 5s CD</span>` }
    },
    stormforged_hammer: {
      excerpt: { es: "Un martillo forjado en el corazón de la tormenta, crepitando con la furia de un antiguo dios del cielo." },
      evolution: { es: "Se convierte en Thor, señor del trueno" },
      descHtml: { es: `<span style="color:#FFAA00">Stormforged Hammer</span><br><span style="color:#AAAAAA">Un martillo forjado en el corazón de la tormenta, crepitando con la furia de un antiguo dios del cielo.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Lightning Conductor</span>: inmune al rayo, y el daño de rayo que causas aumenta un 35%.<br><span style="color:#55FFFF">[In slot] Mjolnir's Coating</span>: 15% de probabilidad en un golpe físico de replicar el 20% del daño como rayo, con un trueno y chispas.<br><span style="color:#55FFFF">[Toggle] Storm's Might</span>: +15% de daño físico y Strength I. Cuesta 150 MP/s.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Bolt Strike </span><span style="color:#AAAAAA">(Press)</span>: invoca un rayo en tu cursor por 100 de daño en 5 bloques. <span style="color:#AAAAAA">2000 MP, 10s CD</span><br><span style="color:#FFFF55">[Mode 2] Fusion Bolt </span><span style="color:#AAAAAA">(Hold)</span>: carga y embiste por 60 de daño; si Stormcall fue tu última habilidad, los objetivos reciben +40 de daño y Paralysis. <span style="color:#AAAAAA">500 MP, 20s CD</span><br><span style="color:#FFFF55">[Mode 3] Stormcall </span><span style="color:#AAAAAA">(Press)</span>: un enorme rayo negro en tu cursor por 100 de daño en 5 bloques, con rayos adicionales que se ramifican y sin fuego. <span style="color:#AAAAAA">3000 MP, 20s CD</span>` }
    },
    the_light_bearer: {
      excerpt: { es: "Un niño de otro mundo que carga la última luz a través de la oscuridad. El sol mismo descansa en sus manos, y no dejará que se apague." },
      descHtml: { es: `<span style="color:#FFAA00">The Light Bearer</span><br><span style="color:#AAAAAA">Un niño de otro mundo que carga la última luz a través de la oscuridad. El sol mismo descansa en sus manos, y no dejará que se apague.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[In slot] Bearer of the Sun</span>: Night Vision permanente e inmunidad a Blindness y Darkness. El daño sagrado y de luz que causas aumenta un 50%, y un suave resplandor te sigue.<br><span style="color:#55FFFF">[Always] Hope in the Dark</span>: mientras estás en la oscuridad ganas Regeneration y Strength, brillando con más fuerza donde el mundo es más oscuro.<br><span style="color:#55FFFF">[Toggle] Guiding Light</span>: los aliados en 12 bloques quedan envueltos en calidez, ganando Regeneration y Resistance. Cuesta 100 MP/s.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Rekindle </span><span style="color:#AAAAAA">(Press)</span>: alza el sol para curarte y purificarte a ti y a los aliados cercanos, y abrasa a los enemigos en 10 bloques por 60 de daño sagrado. <span style="color:#AAAAAA">4000 MP, 30s CD</span><br><span style="color:#FFFF55">[Mode 2] Sunray </span><span style="color:#AAAAAA">(Hold)</span>: un círculo de luz carga y luego un haz de luz solar sostenido brota por 25 de daño a 30 bloques de alcance. <span style="color:#AAAAAA">~1000 MP + 300 MP/s, 12s CD</span><br><span style="color:#FFFF55">[Mode 3] One Shot </span><span style="color:#AAAAAA">(Mantener para cargar, soltar)</span>: reúne todo el poder del sol y libera una única lanza de luz perforante por hasta 400 de daño sagrado, ignorando barreras y resistencias. Cuanto más larga la carga, más fuerte el disparo. <span style="color:#AAAAAA">8000 MP, 120s CD</span><br><span style="color:#FFFF55">[Mode 4] ¿Tortitas...? </span><span style="color:#AAAAAA">(Press)</span>: el aperitivo favorito de Niko. Un bocado rápido que otorga un poco de Absorption durante un rato. <span style="color:#AAAAAA">30s CD</span>` }
    },
    trickster_gambit: {
      excerpt: { es: "Astucia y caos hechos manifiestos, siempre tres pasos por delante y siempre sonriendo." },
      evolution: { es: "Se convierte en Loki, señor del caos" },
      descHtml: { es: `<span style="color:#FFAA00">Trickster's Gambit</span><br><span style="color:#AAAAAA">Astucia y caos hechos manifiestos, siempre tres pasos por delante y siempre sonriendo.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Mischief</span>: 15% de probabilidad en un golpe de aplicar un debuff aleatorio (Slowness, Nausea, Weakness o Silence). Inmune a Confusion y Fear.<br><span style="color:#55FFFF">[Toggle] Hidden Trickster</span>: Invisibility total y Night Vision. Desapareces de la lista de tab y el servidor muestra un mensaje falso de salida/entrada al activarlo.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Mirror Image </span><span style="color:#AAAAAA">(Press)</span>: crea un clon ilusorio (con tus efectos activos copiados) que absorbe golpes. <span style="color:#AAAAAA">2000 MP, 25s CD</span><br><span style="color:#FFFF55">[Mode 2] Serpent's Venom </span><span style="color:#AAAAAA">(Hold)</span>: canaliza veneno hacia un objetivo a menos de 5 bloques por 15 de daño por ráfaga más Corrosion; tras 5 s también aplica Paralysis. Fallar lo termina. <span style="color:#AAAAAA">30 MP/tick, 15s CD</span><br><span style="color:#FFFF55">[Mode 3] Nott's Lullaby </span><span style="color:#AAAAAA">(Hold)</span>: lanza un círculo mental (0,75 s), causando 40 de daño de oscuridad una vez y durmiendo al objetivo (Sleep) durante 15 s. <span style="color:#AAAAAA">2500 MP, 25s CD</span>` }
    },
    twin_heavens: {
      excerpt: { es: "La marca de un espadachín invicto que recorrió cada camino como un duelo y solo respondió ante la hoja." },
      descHtml: { es: `<span style="color:#FFAA00">Twin Heavens</span><br><span style="color:#AAAAAA">La marca de un espadachín invicto que recorrió cada camino como un duelo y solo respondió ante la hoja.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Way of the Sword</span>: todo tu daño es más débil salvo que empuñes una katana, tachi u odachi, en cuyo caso tus golpes físicos pegan 2x más fuerte (2,5x al dominarla).<br><span style="color:#55FFFF">[Always] Double Strike</span>: los golpes físicos tienen un 20% de probabilidad (35% al dominarla) de impactar una segunda vez.<br><span style="color:#55FFFF">[Always] Relentless Training</span>: ganas 5 puntos de aprendizaje y dominio donde otros ganan 1.<br><span style="color:#55FFFF">[Always] Frail Magic</span>: causas menos daño mágico, recibes más daño mágico y tu magícula se regenera un poco más lento.<br><span style="color:#55FFFF">[Toggle] Empty Mind</span>: entra en el estado exaltado del santo. Ganas velocidad de movimiento y de ataque por encima de Thought Acceleration, y Foresight: esquivas proyectiles con precisión total y cuerpo a cuerpo un 25% (50% al dominarla), ganas probabilidad de crítico extra, y tus golpes tratan la anulación como mera resistencia mientras ignoran la resistencia.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Crescent Cut </span><span style="color:#AAAAAA">(Press)</span>: libera un tajo de battlewill por el daño de tu arma, 1,5x (2x al dominarla). <span style="color:#AAAAAA">300 Aura, 3s CD</span><br><span style="color:#FFFF55">[Mode 2] Void Step </span><span style="color:#AAAAAA">(Press)</span>: parpadea hasta donde miras (15 bloques, 18 al dominarla), asestando un crítico a todo lo que haya en el camino (+30 de daño, +75 al dominarla). <span style="color:#AAAAAA">100 Aura, 8s CD</span><br><span style="color:#AAAAAA">Difícil de dominar.</span>` }
    },
    unchained_fury: {
      excerpt: { es: "El instinto primigenio de una bestia que nunca debió ser liberada, que se fortalece con cada herida que inflige." },
      evolution: { es: "Se convierte en Fenrir, señor de la cacería" },
      descHtml: { es: `<span style="color:#FFAA00">Unchained Fury</span><br><span style="color:#AAAAAA">El instinto primigenio de una bestia que nunca debió ser liberada, que se fortalece con cada herida que inflige.</span><br><br><span style="color:#AAAAAA">Al aprenderla: otorga Abnormal Condition Resistance y Spiritual Attack Resistance.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[In slot] Beast's Instinct</span>: Speed II y Haste II permanentes.<br><span style="color:#55FFFF">[Always] Predator's Mark</span>: 20% de probabilidad en un golpe físico de causar +20% del daño como oscuridad y aplicar Slowness I durante 4 s.<br><span style="color:#55FFFF">[Toggle] Feral Rage</span>: los golpes consecutivos en 3 s acumulan +5% de daño cada uno, hasta 10 cargas.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Savage Bite </span><span style="color:#AAAAAA">(Press)</span>: se abalanza sobre un objetivo a menos de 6 bloques por 100 de daño de oscuridad y Fatal Poison IV. Por debajo de la mitad del HP: también Fear y drena 500 MP. <span style="color:#AAAAAA">2500 MP, 25s CD</span><br><span style="color:#FFFF55">[Mode 2] Howl </span><span style="color:#AAAAAA">(Press)</span>: Fear III y Silence durante 10 s a todos los enemigos en 15 bloques. <span style="color:#AAAAAA">4000 MP, 45s CD</span><br><span style="color:#FFFF55">[Mode 3] Hunting Surge </span><span style="color:#AAAAAA">(Hold)</span>: carga y luego una enorme embestida por 80 de daño de oscuridad con empuje; Slowness III al impactar con 5+ cargas de Feral Rage. <span style="color:#AAAAAA">2000 MP, 20s CD</span>` }
    },
    vanir_blessing: {
      excerpt: { es: "Una bendición tejida a partes iguales de seidr y guerra, otorgada por quien reclama a los dignos para sí." },
      evolution: { es: "Se convierte en Freya, señora de la guerra" },
      descHtml: { es: `<span style="color:#FFAA00">Vanir's Blessing</span><br><span style="color:#AAAAAA">Una bendición tejida a partes iguales de seidr y guerra, otorgada por quien reclama a los dignos para sí.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Valkyrie's Grace</span>: los golpes físicos sobre ti tienen un 15% de probabilidad de ser esquivados. Cada golpe físico que asestas acumula Fragility en el objetivo, hasta Fragility V.<br><span style="color:#55FFFF">[Toggle] Shield of Vanaheim</span>: +8 de armadura, y los aliados en 15 bloques reciben Protection. Tras esquivar un golpe, tu siguiente ataque causa +20 de daño extra.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Valkyrie's Touch </span><span style="color:#AAAAAA">(Press)</span>: cura y purifica por completo a un aliado cercano (o a ti mismo). <span style="color:#AAAAAA">3000 MP, 25s CD</span><br><span style="color:#FFFF55">[Mode 2] Folkvang's Claim </span><span style="color:#AAAAAA">(Hold)</span>: canaliza a través de un círculo sagrado; un rayo de atracción causa 15 de daño sagrado por ráfaga y arrastra al primer objetivo hacia ti. <span style="color:#AAAAAA">20 MP/tick, 15s CD</span><br><span style="color:#FFFF55">[Mode 3] Seidr Rain </span><span style="color:#AAAAAA">(Hold)</span>: lanza (0,75 s, 0,3 s al dominarla) y luego 22 flechas de luz llueven sobre el área objetivo por 25 de daño cada una. <span style="color:#AAAAAA">3000 MP, 25s CD</span>` }
    },
    windcaller: {
      excerpt: { es: "Un prodigio nato al que los espíritus del viento adoran. La brisa te lleva y tu magia fluye con facilidad." },
      descHtml: { es: `<span style="color:#FFAA00">Windcaller</span><br><span style="color:#AAAAAA">Un prodigio nato al que los espíritus del viento adoran. La brisa te lleva y tu magia fluye con facilidad.</span><br><br><span style="color:#AAAAAA">Al obtener esta skill también recibes Mana Manipulation.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[In Slot] Gifted</span>: un talento natural. El aprendizaje de habilidades es más rápido y la ganancia de magícula sube un 25%.<br><span style="color:#55FFFF">[In Slot] Mana Prodigy</span>: la magia que lanzas causa un 20% más, y tu magia de viento un 30% más.<br><span style="color:#55FFFF">[In Slot] Wind's Embrace</span>: el viento siempre te sostiene, así que no recibes daño por caída.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Wind Blade </span><span style="color:#AAAAAA">(Press)</span>: libera una hoja de viento cortante. <span style="color:#AAAAAA">300 MP, 3s CD</span><br><span style="color:#FFFF55">[Mode 2] Sylph's Grace </span><span style="color:#AAAAAA">(Hold)</span>: mantén para cabalgar el viento en vuelo. Drena mucho MP por segundo y dura solo mientras aguante tu magícula. <span style="color:#AAAAAA">Sin cooldown</span><br><span style="color:#FFFF55">[Mode 3] Wind Protection </span><span style="color:#AAAAAA">(Press)</span>: envuélvete en el efecto Wind Protection. <span style="color:#AAAAAA">400 MP, 15s CD</span>` }
    },
    world_serpent_coil: {
      excerpt: { es: "El anillo aplastante de una serpiente tan vasta como para rodear el mundo. Su veneno devora todas las cosas desde dentro." },
      evolution: { es: "Se convierte en Jörmungandr, señor del abismo" },
      descHtml: { es: `<span style="color:#FFAA00">World Serpent's Coil</span><br><span style="color:#AAAAAA">El anillo aplastante de una serpiente tan vasta como para rodear el mundo. Su veneno devora todas las cosas desde dentro.</span><br><br><span style="color:#AAAAAA">Al aprenderla: otorga Poison Resistance. Water Breathing permanente mientras esté equipada.</span><br><br><span style="font-weight:bold">Pasiva</span><br><span style="color:#55FFFF">[Always] Venomous</span>: cada golpe físico acumula Poison; con 5 cargas el objetivo queda Paralysed.<br><span style="color:#55FFFF">[Toggle] Scaled Hide</span>: +10 de armadura, y el veneno se purga continuamente de ti por debajo del 30% de HP.<br><span style="color:#55FFFF">[Toggle] Deep Pressure</span>: los enemigos en 6 bloques son ralentizados continuamente.<br><br><span style="font-weight:bold">Activa</span><br><span style="color:#FFFF55">[Mode 1] Coil </span><span style="color:#AAAAAA">(Hold)</span>: presión aplastante de serpiente, un aura de haki de señor demonio más 15 de daño de agua, Slowness II y Corrosion por ráfaga en 10 bloques. <span style="color:#AAAAAA">60 MP/tick, 15s CD</span><br><span style="color:#FFFF55">[Mode 2] Tide Surge </span><span style="color:#AAAAAA">(Press)</span>: una gran ola de agua por 60 de daño con Slowness II y Burden. <span style="color:#AAAAAA">5000 MP, 30s CD</span><br><span style="color:#FFFF55">[Mode 3] Serpent Breath </span><span style="color:#AAAAAA">(Press)</span>: una ráfaga de aliento venenoso por 35 de daño de veneno. <span style="color:#AAAAAA">1500 MP, 10s CD</span>` }
    }
  },
  intrinsics: {
    blood_frenzy: {
      race: { es: "Linaje Vampiro (Ghoul → Vampire → Vampire Lord)" },
      excerpt: { es: "El hambre del linaje Vampiro (Ghoul → Vampire → Vampire Lord → Vampire Overcomer/Divine Vampire)." },
      descHtml: { es: `<span style="color:#AA0000">[Intrinsic Skill — Toggle]</span><br>El hambre del linaje Vampiro (Ghoul → Vampire → Vampire Lord → Vampire Overcomer/Divine Vampire).<br><br><span style="font-weight:bold">Toggle</span>: mientras esté activa, tu sed de sangre crece —literalmente, como <span style="color:#FF5555">Insanity</span>— hasta el nivel <span style="color:#FFFF55">10</span> (aproximadamente un minuto para llegar al máximo). Cuanto más sube, más crecen tu robo de vida (hasta el <span style="color:#FF5555">100%</span> del daño causado) y tu daño de salida (hasta <span style="color:#FFAA00">+20%</span>), a costa de todo lo que la propia Insanity conlleva. Desactivarla lo reinicia.` }
    },
    draconic_awakening: {
      race: { es: "Linaje Lizardman/Dragonewt" },
      excerpt: { es: "La sangre latente de los dragones que duerme en el linaje lagarto." },
      descHtml: { es: `<span style="color:#AA0000">[Intrinsic Skill]</span><br>La sangre latente de los dragones que duerme en el linaje lagarto.<br><br><span style="font-weight:bold">Press</span> para despertarla: tu <span style="color:#55FF55">HP, magícula y aura se restauran por completo</span>, tu cuerpo se hincha en un <span style="color:#AA0000">dragón colosal</span>, tu vitalidad se dispara (<span style="color:#FF5555">×3 de HP máx.</span>) y <span style="color:#FFAA00">todo tipo de daño que causas</span> —físico y mágico por igual— se <span style="color:#FF55FF">duplica (×2)</span>. Tu <span style="color:#55FF55">alcance escala con tu tamaño</span> y tu <span style="color:#55FF55">velocidad, salto y agarre</span> aumentan en consecuencia, así que sigues siendo tan ágil como cuando eras pequeño.<br><br><span style="color:#AAAAAA">Coste: </span><span style="color:#55FFFF">5.000 MP </span><span style="color:#AAAAAA">+ </span><span style="color:#FF5555">5.000 AP</span><span style="color:#AAAAAA">. Dura </span><span style="color:#FFFF55">1 minuto </span><span style="color:#AAAAAA">(</span><span style="color:#FFFF55">2 </span><span style="color:#AAAAAA">una vez dominada). Cooldown: </span><span style="color:#FF5555">60 minutos</span><span style="color:#AAAAAA">. Diez usos la dominan.<br><br></span><span style="color:#AA0000">Retroceso:</span> cuando termina, la tensión te cuesta el <span style="color:#FF5555">5% de tu EP máx. de forma permanente</span> y te deja con <span style="color:#FF5555">Weakness</span>, <span style="color:#FF5555">Slowness</span>, <span style="color:#FF5555">Mining Fatigue</span> y <span style="color:#FF5555">×0,75 de daño de salida</span> durante <span style="color:#FFFF55">20 minutos</span><span style="color:#AAAAAA">.</span>` }
    },
    dwarf_forgemaster: {
      race: { es: "Dwarf" },
      excerpt: { es: "Nacida de la tierra y la piedra, la constitución física de un Dwarf es tan impenetrable como las montañas que llama hogar. Su piel desvía los golpes como acero forjado, y..." },
      descHtml: { es: `Nacida de la tierra y la piedra, la constitución física de un Dwarf es tan impenetrable como las montañas que llama hogar. Su piel desvía los golpes como acero forjado, y su innato dominio del subsuelo les otorga una velocidad incansable al moldear la tierra.` }
    },
    elemental_resonance: {
      race: { es: "Elemental" },
      excerpt: { es: "El cuerpo del espíritu está en sintonía con los elementos mismos." },
      descHtml: { es: `<span style="color:#55FFFF">[Intrinsic Skill]</span><br>El cuerpo del espíritu está en sintonía con los elementos mismos.<br><br><span style="font-weight:bold">Pasiva</span>: cada tipo de daño elemental que causas se potencia <span style="color:#FF55FF">(×1,3)</span> — Water, Fire, Earth, Wind, Light, Dark y Space (y sus formas Ice, Lightning y Gravity).` }
    },
    elf_mana_flow: {
      race: { es: "Elf" },
      excerpt: { es: "Como seres profundamente en sintonía con la naturaleza y el entramado mágico del mundo, los Elfos poseen una conexión profunda con los magículas. Aunque esta afinidad pura les impide..." },
      descHtml: { es: `Como seres profundamente en sintonía con la naturaleza y el entramado mágico del mundo, los Elfos poseen una conexión profunda con los magículas. Aunque esta afinidad pura les impide manifestar aura física, su esencia espiritual permite que su maná se reponga bastante más rápido que el de otras razas.` }
    },
    goblin_greed: {
      race: { es: "Goblin" },
      excerpt: { es: "El instinto acaparador del goblin: la riqueza es poder." },
      descHtml: { es: `<span style="color:#FFAA00">[Intrinsic Skill]</span><br>El instinto acaparador del goblin: la riqueza es poder.<br><br><span style="font-weight:bold">Press</span> para abrir tu <span style="color:#FFAA00">banco de monedas</span>. Las monedas depositadas se convierten en un tesoro de <span style="color:#FFFF55">valor</span> (Bronze 1, Silver 100, Gold 10.000, Stellar 1.000.000); puedes retirar monedas en cualquier momento.<br><br><span style="font-weight:bold">Pasiva</span>: tus estadísticas de combate (Ataque, HP, Armadura, Velocidad) escalan con tu tesoro por niveles, alcanzando su tope con <span style="color:#FFFF55">1.000.000</span> de valor. Guardar más sigue siendo tu dinero — simplemente no otorga más poder.` }
    },
    human_ambition: {
      race: { es: "Human" },
      excerpt: { es: "Impulsados por un espíritu inquebrantable y un potencial sin límites, los humanos poseen una capacidad extraordinaria de crecimiento. Acumulan experiencia y dominan nuevas habilidades..." },
      descHtml: { es: `Impulsados por un espíritu inquebrantable y un potencial sin límites, los humanos poseen una capacidad extraordinaria de crecimiento. Acumulan experiencia y dominan nuevas habilidades a un ritmo sin precedentes.` }
    },
    merfolk_water_blessing: {
      race: { es: "Merfolk" },
      excerpt: { es: "Los verdaderos superdepredadores de las profundidades. A los Merfolk apenas les hace daño la magia de agua. Cuando los abraza la lluvia o se sumergen en su dominio acuático, sus..." },
      descHtml: { es: `Los verdaderos superdepredadores de las profundidades. A los Merfolk apenas les hace daño la magia de agua. Cuando los abraza la lluvia o se sumergen en su dominio acuático, sus escamas se endurecen en una armadura cristalina impenetrable, y corrientes primigenias recorren sus venas, potenciando enormemente su fuerza física, velocidad y vitalidad.` }
    }
  }
};
